package enums

type AdcreativelinkdataimageoverlayspecThemeColor string

const (
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundX000000TextFfffff AdcreativelinkdataimageoverlayspecThemeColor = "background_000000_text_ffffff"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundX0090ffTextFfffff AdcreativelinkdataimageoverlayspecThemeColor = "background_0090ff_text_ffffff"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundX00af4cTextFfffff AdcreativelinkdataimageoverlayspecThemeColor = "background_00af4c_text_ffffff"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundX595959TextFfffff AdcreativelinkdataimageoverlayspecThemeColor = "background_595959_text_ffffff"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundX755ddeTextFfffff AdcreativelinkdataimageoverlayspecThemeColor = "background_755dde_text_ffffff"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundE50900TextFfffff  AdcreativelinkdataimageoverlayspecThemeColor = "background_e50900_text_ffffff"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundF23474TextFfffff  AdcreativelinkdataimageoverlayspecThemeColor = "background_f23474_text_ffffff"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundF78400TextFfffff  AdcreativelinkdataimageoverlayspecThemeColor = "background_f78400_text_ffffff"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundFfffffTextX000000 AdcreativelinkdataimageoverlayspecThemeColor = "background_ffffff_text_000000"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundFfffffTextX007ad0 AdcreativelinkdataimageoverlayspecThemeColor = "background_ffffff_text_007ad0"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundFfffffTextX009c2a AdcreativelinkdataimageoverlayspecThemeColor = "background_ffffff_text_009c2a"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundFfffffTextX646464 AdcreativelinkdataimageoverlayspecThemeColor = "background_ffffff_text_646464"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundFfffffTextX755dde AdcreativelinkdataimageoverlayspecThemeColor = "background_ffffff_text_755dde"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundFfffffTextC91b00  AdcreativelinkdataimageoverlayspecThemeColor = "background_ffffff_text_c91b00"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundFfffffTextF23474  AdcreativelinkdataimageoverlayspecThemeColor = "background_ffffff_text_f23474"
	AdcreativelinkdataimageoverlayspecThemeColorBackgroundFfffffTextF78400  AdcreativelinkdataimageoverlayspecThemeColor = "background_ffffff_text_f78400"
)

func (value AdcreativelinkdataimageoverlayspecThemeColor) String() string {
	return string(value)
}
