package enums

type AdcreativelinkdatacustomoverlayspecBackgroundColor string

const (
	AdcreativelinkdatacustomoverlayspecBackgroundColorBackgroundX000000 AdcreativelinkdatacustomoverlayspecBackgroundColor = "background_000000"
	AdcreativelinkdatacustomoverlayspecBackgroundColorBackgroundX0090ff AdcreativelinkdatacustomoverlayspecBackgroundColor = "background_0090ff"
	AdcreativelinkdatacustomoverlayspecBackgroundColorBackgroundX00af4c AdcreativelinkdatacustomoverlayspecBackgroundColor = "background_00af4c"
	AdcreativelinkdatacustomoverlayspecBackgroundColorBackgroundX595959 AdcreativelinkdatacustomoverlayspecBackgroundColor = "background_595959"
	AdcreativelinkdatacustomoverlayspecBackgroundColorBackgroundX755dde AdcreativelinkdatacustomoverlayspecBackgroundColor = "background_755dde"
	AdcreativelinkdatacustomoverlayspecBackgroundColorBackgroundE50900  AdcreativelinkdatacustomoverlayspecBackgroundColor = "background_e50900"
	AdcreativelinkdatacustomoverlayspecBackgroundColorBackgroundF23474  AdcreativelinkdatacustomoverlayspecBackgroundColor = "background_f23474"
	AdcreativelinkdatacustomoverlayspecBackgroundColorBackgroundF78400  AdcreativelinkdatacustomoverlayspecBackgroundColor = "background_f78400"
	AdcreativelinkdatacustomoverlayspecBackgroundColorBackgroundFfffff  AdcreativelinkdatacustomoverlayspecBackgroundColor = "background_ffffff"
)

func (value AdcreativelinkdatacustomoverlayspecBackgroundColor) String() string {
	return string(value)
}
