package enums

type AdaccountinsightsBreakdownsEnumParam string

const (
	AdaccountinsightsBreakdownsEnumParamAdExtensionDomain                         AdaccountinsightsBreakdownsEnumParam = "ad_extension_domain"
	AdaccountinsightsBreakdownsEnumParamAdExtensionURL                            AdaccountinsightsBreakdownsEnumParam = "ad_extension_url"
	AdaccountinsightsBreakdownsEnumParamAdFormatAsset                             AdaccountinsightsBreakdownsEnumParam = "ad_format_asset"
	AdaccountinsightsBreakdownsEnumParamAge                                       AdaccountinsightsBreakdownsEnumParam = "age"
	AdaccountinsightsBreakdownsEnumParamAppID                                     AdaccountinsightsBreakdownsEnumParam = "app_id"
	AdaccountinsightsBreakdownsEnumParamBodyAsset                                 AdaccountinsightsBreakdownsEnumParam = "body_asset"
	AdaccountinsightsBreakdownsEnumParamBreakdownAdObjective                      AdaccountinsightsBreakdownsEnumParam = "breakdown_ad_objective"
	AdaccountinsightsBreakdownsEnumParamBreakdownReportingAdID                    AdaccountinsightsBreakdownsEnumParam = "breakdown_reporting_ad_id"
	AdaccountinsightsBreakdownsEnumParamCallToActionAsset                         AdaccountinsightsBreakdownsEnumParam = "call_to_action_asset"
	AdaccountinsightsBreakdownsEnumParamCoarseConversionValue                     AdaccountinsightsBreakdownsEnumParam = "coarse_conversion_value"
	AdaccountinsightsBreakdownsEnumParamComscoreMarket                            AdaccountinsightsBreakdownsEnumParam = "comscore_market"
	AdaccountinsightsBreakdownsEnumParamConversionDestination                     AdaccountinsightsBreakdownsEnumParam = "conversion_destination"
	AdaccountinsightsBreakdownsEnumParamCountry                                   AdaccountinsightsBreakdownsEnumParam = "country"
	AdaccountinsightsBreakdownsEnumParamCreativeAutomationAssetID                 AdaccountinsightsBreakdownsEnumParam = "creative_automation_asset_id"
	AdaccountinsightsBreakdownsEnumParamCreativeRelaxationAssetType               AdaccountinsightsBreakdownsEnumParam = "creative_relaxation_asset_type"
	AdaccountinsightsBreakdownsEnumParamCrmAdvertiserL12TerritoryIds              AdaccountinsightsBreakdownsEnumParam = "crm_advertiser_l12_territory_ids"
	AdaccountinsightsBreakdownsEnumParamCrmAdvertiserSubverticalID                AdaccountinsightsBreakdownsEnumParam = "crm_advertiser_subvertical_id"
	AdaccountinsightsBreakdownsEnumParamCrmAdvertiserVerticalID                   AdaccountinsightsBreakdownsEnumParam = "crm_advertiser_vertical_id"
	AdaccountinsightsBreakdownsEnumParamCrmUltAdvertiserID                        AdaccountinsightsBreakdownsEnumParam = "crm_ult_advertiser_id"
	AdaccountinsightsBreakdownsEnumParamDescriptionAsset                          AdaccountinsightsBreakdownsEnumParam = "description_asset"
	AdaccountinsightsBreakdownsEnumParamDevicePlatform                            AdaccountinsightsBreakdownsEnumParam = "device_platform"
	AdaccountinsightsBreakdownsEnumParamDma                                       AdaccountinsightsBreakdownsEnumParam = "dma"
	AdaccountinsightsBreakdownsEnumParamExistingPostID                            AdaccountinsightsBreakdownsEnumParam = "existing_post_id"
	AdaccountinsightsBreakdownsEnumParamFidelityType                              AdaccountinsightsBreakdownsEnumParam = "fidelity_type"
	AdaccountinsightsBreakdownsEnumParamFlexibleFormatAssetType                   AdaccountinsightsBreakdownsEnumParam = "flexible_format_asset_type"
	AdaccountinsightsBreakdownsEnumParamFrequencyValue                            AdaccountinsightsBreakdownsEnumParam = "frequency_value"
	AdaccountinsightsBreakdownsEnumParamGenAiAssetType                            AdaccountinsightsBreakdownsEnumParam = "gen_ai_asset_type"
	AdaccountinsightsBreakdownsEnumParamGender                                    AdaccountinsightsBreakdownsEnumParam = "gender"
	AdaccountinsightsBreakdownsEnumParamHourlyStatsAggregatedByAdvertiserTimeZone AdaccountinsightsBreakdownsEnumParam = "hourly_stats_aggregated_by_advertiser_time_zone"
	AdaccountinsightsBreakdownsEnumParamHourlyStatsAggregatedByAudienceTimeZone   AdaccountinsightsBreakdownsEnumParam = "hourly_stats_aggregated_by_audience_time_zone"
	AdaccountinsightsBreakdownsEnumParamHsid                                      AdaccountinsightsBreakdownsEnumParam = "hsid"
	AdaccountinsightsBreakdownsEnumParamImageAsset                                AdaccountinsightsBreakdownsEnumParam = "image_asset"
	AdaccountinsightsBreakdownsEnumParamImpressionDevice                          AdaccountinsightsBreakdownsEnumParam = "impression_device"
	AdaccountinsightsBreakdownsEnumParamImpressionViewTimeAdvertiserHourV2        AdaccountinsightsBreakdownsEnumParam = "impression_view_time_advertiser_hour_v2"
	AdaccountinsightsBreakdownsEnumParamInstagramAdsFollowType                    AdaccountinsightsBreakdownsEnumParam = "instagram_ads_follow_type"
	AdaccountinsightsBreakdownsEnumParamInstagramAdsInstagramMediaProductType     AdaccountinsightsBreakdownsEnumParam = "instagram_ads_instagram_media_product_type"
	AdaccountinsightsBreakdownsEnumParamInstagramAdsTimeSinceCreationBucket       AdaccountinsightsBreakdownsEnumParam = "instagram_ads_time_since_creation_bucket"
	AdaccountinsightsBreakdownsEnumParamInternalCampaignID                        AdaccountinsightsBreakdownsEnumParam = "internal_campaign_id"
	AdaccountinsightsBreakdownsEnumParamIsAutoAdvance                             AdaccountinsightsBreakdownsEnumParam = "is_auto_advance"
	AdaccountinsightsBreakdownsEnumParamIsConversionIDModeled                     AdaccountinsightsBreakdownsEnumParam = "is_conversion_id_modeled"
	AdaccountinsightsBreakdownsEnumParamIsRenderedAsDelayedSkipAd                 AdaccountinsightsBreakdownsEnumParam = "is_rendered_as_delayed_skip_ad"
	AdaccountinsightsBreakdownsEnumParamLandingDestination                        AdaccountinsightsBreakdownsEnumParam = "landing_destination"
	AdaccountinsightsBreakdownsEnumParamLinkURLAsset                              AdaccountinsightsBreakdownsEnumParam = "link_url_asset"
	AdaccountinsightsBreakdownsEnumParamMarketingMessagesBtnName                  AdaccountinsightsBreakdownsEnumParam = "marketing_messages_btn_name"
	AdaccountinsightsBreakdownsEnumParamMdsaLandingDestination                    AdaccountinsightsBreakdownsEnumParam = "mdsa_landing_destination"
	AdaccountinsightsBreakdownsEnumParamMediaAssetURL                             AdaccountinsightsBreakdownsEnumParam = "media_asset_url"
	AdaccountinsightsBreakdownsEnumParamMediaCreator                              AdaccountinsightsBreakdownsEnumParam = "media_creator"
	AdaccountinsightsBreakdownsEnumParamMediaDestinationURL                       AdaccountinsightsBreakdownsEnumParam = "media_destination_url"
	AdaccountinsightsBreakdownsEnumParamMediaFormat                               AdaccountinsightsBreakdownsEnumParam = "media_format"
	AdaccountinsightsBreakdownsEnumParamMediaOriginURL                            AdaccountinsightsBreakdownsEnumParam = "media_origin_url"
	AdaccountinsightsBreakdownsEnumParamMediaTextContent                          AdaccountinsightsBreakdownsEnumParam = "media_text_content"
	AdaccountinsightsBreakdownsEnumParamMediaType                                 AdaccountinsightsBreakdownsEnumParam = "media_type"
	AdaccountinsightsBreakdownsEnumParamMmm                                       AdaccountinsightsBreakdownsEnumParam = "mmm"
	AdaccountinsightsBreakdownsEnumParamOverlapSegment                            AdaccountinsightsBreakdownsEnumParam = "overlap_segment"
	AdaccountinsightsBreakdownsEnumParamPaCreatorIgHandle                         AdaccountinsightsBreakdownsEnumParam = "pa_creator_ig_handle"
	AdaccountinsightsBreakdownsEnumParamPlacePageID                               AdaccountinsightsBreakdownsEnumParam = "place_page_id"
	AdaccountinsightsBreakdownsEnumParamPlatformPosition                          AdaccountinsightsBreakdownsEnumParam = "platform_position"
	AdaccountinsightsBreakdownsEnumParamPostbackSequenceIndex                     AdaccountinsightsBreakdownsEnumParam = "postback_sequence_index"
	AdaccountinsightsBreakdownsEnumParamProductBrandBreakdown                     AdaccountinsightsBreakdownsEnumParam = "product_brand_breakdown"
	AdaccountinsightsBreakdownsEnumParamProductCategoryBreakdown                  AdaccountinsightsBreakdownsEnumParam = "product_category_breakdown"
	AdaccountinsightsBreakdownsEnumParamProductCustomLabelX0Breakdown             AdaccountinsightsBreakdownsEnumParam = "product_custom_label_0_breakdown"
	AdaccountinsightsBreakdownsEnumParamProductCustomLabelX1Breakdown             AdaccountinsightsBreakdownsEnumParam = "product_custom_label_1_breakdown"
	AdaccountinsightsBreakdownsEnumParamProductCustomLabelX2Breakdown             AdaccountinsightsBreakdownsEnumParam = "product_custom_label_2_breakdown"
	AdaccountinsightsBreakdownsEnumParamProductCustomLabelX3Breakdown             AdaccountinsightsBreakdownsEnumParam = "product_custom_label_3_breakdown"
	AdaccountinsightsBreakdownsEnumParamProductCustomLabelX4Breakdown             AdaccountinsightsBreakdownsEnumParam = "product_custom_label_4_breakdown"
	AdaccountinsightsBreakdownsEnumParamProductGroupContentIDBreakdown            AdaccountinsightsBreakdownsEnumParam = "product_group_content_id_breakdown"
	AdaccountinsightsBreakdownsEnumParamProductID                                 AdaccountinsightsBreakdownsEnumParam = "product_id"
	AdaccountinsightsBreakdownsEnumParamPublisherPlatform                         AdaccountinsightsBreakdownsEnumParam = "publisher_platform"
	AdaccountinsightsBreakdownsEnumParamRedownload                                AdaccountinsightsBreakdownsEnumParam = "redownload"
	AdaccountinsightsBreakdownsEnumParamReelsTrendingTopic                        AdaccountinsightsBreakdownsEnumParam = "reels_trending_topic"
	AdaccountinsightsBreakdownsEnumParamRegion                                    AdaccountinsightsBreakdownsEnumParam = "region"
	AdaccountinsightsBreakdownsEnumParamRtaUgcTopic                               AdaccountinsightsBreakdownsEnumParam = "rta_ugc_topic"
	AdaccountinsightsBreakdownsEnumParamRuleSetID                                 AdaccountinsightsBreakdownsEnumParam = "rule_set_id"
	AdaccountinsightsBreakdownsEnumParamRuleSetName                               AdaccountinsightsBreakdownsEnumParam = "rule_set_name"
	AdaccountinsightsBreakdownsEnumParamSignalSourceBucket                        AdaccountinsightsBreakdownsEnumParam = "signal_source_bucket"
	AdaccountinsightsBreakdownsEnumParamSkanCampaignID                            AdaccountinsightsBreakdownsEnumParam = "skan_campaign_id"
	AdaccountinsightsBreakdownsEnumParamSkanConversionID                          AdaccountinsightsBreakdownsEnumParam = "skan_conversion_id"
	AdaccountinsightsBreakdownsEnumParamSkanVersion                               AdaccountinsightsBreakdownsEnumParam = "skan_version"
	AdaccountinsightsBreakdownsEnumParamSotAttributionModelType                   AdaccountinsightsBreakdownsEnumParam = "sot_attribution_model_type"
	AdaccountinsightsBreakdownsEnumParamSotAttributionWindow                      AdaccountinsightsBreakdownsEnumParam = "sot_attribution_window"
	AdaccountinsightsBreakdownsEnumParamSotChannel                                AdaccountinsightsBreakdownsEnumParam = "sot_channel"
	AdaccountinsightsBreakdownsEnumParamSotEventType                              AdaccountinsightsBreakdownsEnumParam = "sot_event_type"
	AdaccountinsightsBreakdownsEnumParamSotSource                                 AdaccountinsightsBreakdownsEnumParam = "sot_source"
	AdaccountinsightsBreakdownsEnumParamStandardEventContentType                  AdaccountinsightsBreakdownsEnumParam = "standard_event_content_type"
	AdaccountinsightsBreakdownsEnumParamTitleAsset                                AdaccountinsightsBreakdownsEnumParam = "title_asset"
	AdaccountinsightsBreakdownsEnumParamUserPersonaID                             AdaccountinsightsBreakdownsEnumParam = "user_persona_id"
	AdaccountinsightsBreakdownsEnumParamUserPersonaName                           AdaccountinsightsBreakdownsEnumParam = "user_persona_name"
	AdaccountinsightsBreakdownsEnumParamVideoAsset                                AdaccountinsightsBreakdownsEnumParam = "video_asset"
	AdaccountinsightsBreakdownsEnumParamZip                                       AdaccountinsightsBreakdownsEnumParam = "zip"
)

func (value AdaccountinsightsBreakdownsEnumParam) String() string {
	return string(value)
}
