package enums

type AdaccountCurrency string

const (
	AdaccountCurrencyAed AdaccountCurrency = "AED"
	AdaccountCurrencyArs AdaccountCurrency = "ARS"
	AdaccountCurrencyAud AdaccountCurrency = "AUD"
	AdaccountCurrencyBdt AdaccountCurrency = "BDT"
	AdaccountCurrencyBob AdaccountCurrency = "BOB"
	AdaccountCurrencyBrl AdaccountCurrency = "BRL"
	AdaccountCurrencyCad AdaccountCurrency = "CAD"
	AdaccountCurrencyChf AdaccountCurrency = "CHF"
	AdaccountCurrencyClp AdaccountCurrency = "CLP"
	AdaccountCurrencyCny AdaccountCurrency = "CNY"
	AdaccountCurrencyCop AdaccountCurrency = "COP"
	AdaccountCurrencyCrc AdaccountCurrency = "CRC"
	AdaccountCurrencyCzk AdaccountCurrency = "CZK"
	AdaccountCurrencyDkk AdaccountCurrency = "DKK"
	AdaccountCurrencyDzd AdaccountCurrency = "DZD"
	AdaccountCurrencyEgp AdaccountCurrency = "EGP"
	AdaccountCurrencyEur AdaccountCurrency = "EUR"
	AdaccountCurrencyGbp AdaccountCurrency = "GBP"
	AdaccountCurrencyGtq AdaccountCurrency = "GTQ"
	AdaccountCurrencyHkd AdaccountCurrency = "HKD"
	AdaccountCurrencyHnl AdaccountCurrency = "HNL"
	AdaccountCurrencyHuf AdaccountCurrency = "HUF"
	AdaccountCurrencyIdr AdaccountCurrency = "IDR"
	AdaccountCurrencyIls AdaccountCurrency = "ILS"
	AdaccountCurrencyInr AdaccountCurrency = "INR"
	AdaccountCurrencyIsk AdaccountCurrency = "ISK"
	AdaccountCurrencyJpy AdaccountCurrency = "JPY"
	AdaccountCurrencyKes AdaccountCurrency = "KES"
	AdaccountCurrencyKrw AdaccountCurrency = "KRW"
	AdaccountCurrencyLkr AdaccountCurrency = "LKR"
	AdaccountCurrencyMop AdaccountCurrency = "MOP"
	AdaccountCurrencyMxn AdaccountCurrency = "MXN"
	AdaccountCurrencyMyr AdaccountCurrency = "MYR"
	AdaccountCurrencyNgn AdaccountCurrency = "NGN"
	AdaccountCurrencyNio AdaccountCurrency = "NIO"
	AdaccountCurrencyNok AdaccountCurrency = "NOK"
	AdaccountCurrencyNzd AdaccountCurrency = "NZD"
	AdaccountCurrencyPen AdaccountCurrency = "PEN"
	AdaccountCurrencyPhp AdaccountCurrency = "PHP"
	AdaccountCurrencyPkr AdaccountCurrency = "PKR"
	AdaccountCurrencyPln AdaccountCurrency = "PLN"
	AdaccountCurrencyPyg AdaccountCurrency = "PYG"
	AdaccountCurrencyQar AdaccountCurrency = "QAR"
	AdaccountCurrencyRon AdaccountCurrency = "RON"
	AdaccountCurrencySar AdaccountCurrency = "SAR"
	AdaccountCurrencySek AdaccountCurrency = "SEK"
	AdaccountCurrencySgd AdaccountCurrency = "SGD"
	AdaccountCurrencyThb AdaccountCurrency = "THB"
	AdaccountCurrencyTry AdaccountCurrency = "TRY"
	AdaccountCurrencyTwd AdaccountCurrency = "TWD"
	AdaccountCurrencyUah AdaccountCurrency = "UAH"
	AdaccountCurrencyUsd AdaccountCurrency = "USD"
	AdaccountCurrencyUyu AdaccountCurrency = "UYU"
	AdaccountCurrencyVnd AdaccountCurrency = "VND"
	AdaccountCurrencyZar AdaccountCurrency = "ZAR"
)

func (value AdaccountCurrency) String() string {
	return string(value)
}
