package enums

type AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam string

const (
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamAnRelaxed        AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "AN_RELAXED"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamAnStandard       AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "AN_STANDARD"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamAnStrict         AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "AN_STRICT"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamFacebookRelaxed  AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "FACEBOOK_RELAXED"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamFacebookStandard AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "FACEBOOK_STANDARD"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamFacebookStrict   AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "FACEBOOK_STRICT"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamFeedDnm          AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "FEED_DNM"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamFeedNestedDnm    AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "FEED_NESTED_DNM"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamFeedRelaxed      AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "FEED_RELAXED"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamFeedStandard     AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "FEED_STANDARD"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamFeedStrict       AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "FEED_STRICT"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamUninitialized    AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "UNINITIALIZED"
	AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParamUnknown          AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam = "UNKNOWN"
)

func (value AdaccountbrandSafetyContentFilterLevelsBrandSafetyContentFilterLevelsEnumParam) String() string {
	return string(value)
}
