package enums

type AdaccountadsetsRegionalRegulatedCategoriesEnumParam string

const (
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX0  AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "0"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX1  AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "1"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX2  AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "2"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX3  AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "3"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX4  AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "4"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX5  AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "5"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX6  AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "6"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX7  AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "7"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX8  AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "8"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX9  AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "9"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX10 AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "10"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX11 AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "11"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX12 AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "12"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX13 AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "13"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX14 AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "14"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX15 AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "15"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX16 AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "16"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX17 AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "17"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX18 AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "18"
	AdaccountadsetsRegionalRegulatedCategoriesEnumParamX19 AdaccountadsetsRegionalRegulatedCategoriesEnumParam = "19"
)

func (value AdaccountadsetsRegionalRegulatedCategoriesEnumParam) String() string {
	return string(value)
}
