package enums

type AdaccountgeneratepreviewsAdFormatEnumParam string

const (
	AdaccountgeneratepreviewsAdFormatEnumParamAudienceNetworkInstreamVideo        AdaccountgeneratepreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_INSTREAM_VIDEO"
	AdaccountgeneratepreviewsAdFormatEnumParamAudienceNetworkInstreamVideoMobile  AdaccountgeneratepreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_INSTREAM_VIDEO_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamAudienceNetworkOutstreamVideo       AdaccountgeneratepreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_OUTSTREAM_VIDEO"
	AdaccountgeneratepreviewsAdFormatEnumParamAudienceNetworkRewardedVideo        AdaccountgeneratepreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_REWARDED_VIDEO"
	AdaccountgeneratepreviewsAdFormatEnumParamBizDiscoFeedMobile                  AdaccountgeneratepreviewsAdFormatEnumParam = "BIZ_DISCO_FEED_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamDesktopFeedStandard                 AdaccountgeneratepreviewsAdFormatEnumParam = "DESKTOP_FEED_STANDARD"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookIfuReelsMobile              AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_IFU_REELS_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookProfileFeedDesktop          AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_PROFILE_FEED_DESKTOP"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookProfileFeedMobile           AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_PROFILE_FEED_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookProfileReelsMobile          AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_PROFILE_REELS_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsBanner                 AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsBannerDesktop          AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_DESKTOP"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsBannerFeedAndroid      AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FEED_ANDROID"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsBannerFeedAndroidLarge AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FEED_ANDROID_LARGE"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsBannerFullscreenIos    AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FULLSCREEN_IOS"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsBannerFullscreenMobile AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FULLSCREEN_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsMobile                 AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsPostloop               AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_POSTLOOP"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsPostloopFeed           AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_POSTLOOP_FEED"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsSimilarProductsMobile  AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_SIMILAR_PRODUCTS_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookReelsSticker                AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_REELS_STICKER"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookStoryMobile                 AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_STORY_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamFacebookStoryStickerMobile          AdaccountgeneratepreviewsAdFormatEnumParam = "FACEBOOK_STORY_STICKER_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramExploreContextual          AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_EXPLORE_CONTEXTUAL"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramExploreGridHome            AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_EXPLORE_GRID_HOME"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramExploreImmersive           AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_EXPLORE_IMMERSIVE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramFeedWeb                    AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_FEED_WEB"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramFeedWebMSite               AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_FEED_WEB_M_SITE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramLeadGenMultiSubmitAds      AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_LEAD_GEN_MULTI_SUBMIT_ADS"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramProfileFeed                AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_PROFILE_FEED"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramProfileReels               AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_PROFILE_REELS"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramReels                      AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_REELS"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramReelsOverlay               AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_REELS_OVERLAY"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramReelsWeb                   AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_REELS_WEB"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramReelsWebMSite              AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_REELS_WEB_M_SITE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramSearchChain                AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_SEARCH_CHAIN"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramSearchGrid                 AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_SEARCH_GRID"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramStandard                   AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_STANDARD"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramStory                      AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_STORY"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramStoryEffectTray            AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_STORY_EFFECT_TRAY"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramStoryWeb                   AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_STORY_WEB"
	AdaccountgeneratepreviewsAdFormatEnumParamInstagramStoryWebMSite              AdaccountgeneratepreviewsAdFormatEnumParam = "INSTAGRAM_STORY_WEB_M_SITE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstantArticleRecirculationAd       AdaccountgeneratepreviewsAdFormatEnumParam = "INSTANT_ARTICLE_RECIRCULATION_AD"
	AdaccountgeneratepreviewsAdFormatEnumParamInstantArticleStandard              AdaccountgeneratepreviewsAdFormatEnumParam = "INSTANT_ARTICLE_STANDARD"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamBannerDesktop               AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_BANNER_DESKTOP"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamBannerFeedIos               AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_BANNER_FEED_IOS"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamBannerFullscreenIos         AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_BANNER_FULLSCREEN_IOS"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamBannerFullscreenMobile      AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_BANNER_FULLSCREEN_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamBannerImmersiveMobile       AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_BANNER_IMMERSIVE_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamBannerMobile                AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_BANNER_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamVideoDesktop                AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_DESKTOP"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamVideoFullscreenIos          AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_FULLSCREEN_IOS"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamVideoFullscreenMobile       AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_FULLSCREEN_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamVideoImage                  AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_IMAGE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamVideoImmersiveMobile        AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_IMMERSIVE_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamInstreamVideoMobile                 AdaccountgeneratepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamJobBrowserDesktop                   AdaccountgeneratepreviewsAdFormatEnumParam = "JOB_BROWSER_DESKTOP"
	AdaccountgeneratepreviewsAdFormatEnumParamJobBrowserMobile                    AdaccountgeneratepreviewsAdFormatEnumParam = "JOB_BROWSER_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamMarketplaceMobile                   AdaccountgeneratepreviewsAdFormatEnumParam = "MARKETPLACE_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamMessengerMobileInboxMedia           AdaccountgeneratepreviewsAdFormatEnumParam = "MESSENGER_MOBILE_INBOX_MEDIA"
	AdaccountgeneratepreviewsAdFormatEnumParamMessengerMobileStoryMedia           AdaccountgeneratepreviewsAdFormatEnumParam = "MESSENGER_MOBILE_STORY_MEDIA"
	AdaccountgeneratepreviewsAdFormatEnumParamMobileBanner                        AdaccountgeneratepreviewsAdFormatEnumParam = "MOBILE_BANNER"
	AdaccountgeneratepreviewsAdFormatEnumParamMobileFeedBasic                     AdaccountgeneratepreviewsAdFormatEnumParam = "MOBILE_FEED_BASIC"
	AdaccountgeneratepreviewsAdFormatEnumParamMobileFeedStandard                  AdaccountgeneratepreviewsAdFormatEnumParam = "MOBILE_FEED_STANDARD"
	AdaccountgeneratepreviewsAdFormatEnumParamMobileFullwidth                     AdaccountgeneratepreviewsAdFormatEnumParam = "MOBILE_FULLWIDTH"
	AdaccountgeneratepreviewsAdFormatEnumParamMobileInterstitial                  AdaccountgeneratepreviewsAdFormatEnumParam = "MOBILE_INTERSTITIAL"
	AdaccountgeneratepreviewsAdFormatEnumParamMobileMediumRectangle               AdaccountgeneratepreviewsAdFormatEnumParam = "MOBILE_MEDIUM_RECTANGLE"
	AdaccountgeneratepreviewsAdFormatEnumParamMobileNative                        AdaccountgeneratepreviewsAdFormatEnumParam = "MOBILE_NATIVE"
	AdaccountgeneratepreviewsAdFormatEnumParamRightColumnStandard                 AdaccountgeneratepreviewsAdFormatEnumParam = "RIGHT_COLUMN_STANDARD"
	AdaccountgeneratepreviewsAdFormatEnumParamSuggestedVideoDesktop               AdaccountgeneratepreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_DESKTOP"
	AdaccountgeneratepreviewsAdFormatEnumParamSuggestedVideoFullscreenMobile      AdaccountgeneratepreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_FULLSCREEN_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamSuggestedVideoImmersiveMobile       AdaccountgeneratepreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_IMMERSIVE_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamSuggestedVideoMobile                AdaccountgeneratepreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamWatchFeedHome                       AdaccountgeneratepreviewsAdFormatEnumParam = "WATCH_FEED_HOME"
	AdaccountgeneratepreviewsAdFormatEnumParamWatchFeedMobile                     AdaccountgeneratepreviewsAdFormatEnumParam = "WATCH_FEED_MOBILE"
	AdaccountgeneratepreviewsAdFormatEnumParamWhatsappStatusMedia                 AdaccountgeneratepreviewsAdFormatEnumParam = "WHATSAPP_STATUS_MEDIA"
)

func (value AdaccountgeneratepreviewsAdFormatEnumParam) String() string {
	return string(value)
}
