package enums

type AdcampaigngroupinsightsBreakdownsEnumParam string

const (
	AdcampaigngroupinsightsBreakdownsEnumParamAdExtensionDomain                         AdcampaigngroupinsightsBreakdownsEnumParam = "ad_extension_domain"
	AdcampaigngroupinsightsBreakdownsEnumParamAdExtensionURL                            AdcampaigngroupinsightsBreakdownsEnumParam = "ad_extension_url"
	AdcampaigngroupinsightsBreakdownsEnumParamAdFormatAsset                             AdcampaigngroupinsightsBreakdownsEnumParam = "ad_format_asset"
	AdcampaigngroupinsightsBreakdownsEnumParamAge                                       AdcampaigngroupinsightsBreakdownsEnumParam = "age"
	AdcampaigngroupinsightsBreakdownsEnumParamAppID                                     AdcampaigngroupinsightsBreakdownsEnumParam = "app_id"
	AdcampaigngroupinsightsBreakdownsEnumParamBodyAsset                                 AdcampaigngroupinsightsBreakdownsEnumParam = "body_asset"
	AdcampaigngroupinsightsBreakdownsEnumParamBreakdownAdObjective                      AdcampaigngroupinsightsBreakdownsEnumParam = "breakdown_ad_objective"
	AdcampaigngroupinsightsBreakdownsEnumParamBreakdownReportingAdID                    AdcampaigngroupinsightsBreakdownsEnumParam = "breakdown_reporting_ad_id"
	AdcampaigngroupinsightsBreakdownsEnumParamCallToActionAsset                         AdcampaigngroupinsightsBreakdownsEnumParam = "call_to_action_asset"
	AdcampaigngroupinsightsBreakdownsEnumParamCoarseConversionValue                     AdcampaigngroupinsightsBreakdownsEnumParam = "coarse_conversion_value"
	AdcampaigngroupinsightsBreakdownsEnumParamComscoreMarket                            AdcampaigngroupinsightsBreakdownsEnumParam = "comscore_market"
	AdcampaigngroupinsightsBreakdownsEnumParamConversionDestination                     AdcampaigngroupinsightsBreakdownsEnumParam = "conversion_destination"
	AdcampaigngroupinsightsBreakdownsEnumParamCountry                                   AdcampaigngroupinsightsBreakdownsEnumParam = "country"
	AdcampaigngroupinsightsBreakdownsEnumParamCreativeAutomationAssetID                 AdcampaigngroupinsightsBreakdownsEnumParam = "creative_automation_asset_id"
	AdcampaigngroupinsightsBreakdownsEnumParamCreativeRelaxationAssetType               AdcampaigngroupinsightsBreakdownsEnumParam = "creative_relaxation_asset_type"
	AdcampaigngroupinsightsBreakdownsEnumParamCrmAdvertiserL12TerritoryIds              AdcampaigngroupinsightsBreakdownsEnumParam = "crm_advertiser_l12_territory_ids"
	AdcampaigngroupinsightsBreakdownsEnumParamCrmAdvertiserSubverticalID                AdcampaigngroupinsightsBreakdownsEnumParam = "crm_advertiser_subvertical_id"
	AdcampaigngroupinsightsBreakdownsEnumParamCrmAdvertiserVerticalID                   AdcampaigngroupinsightsBreakdownsEnumParam = "crm_advertiser_vertical_id"
	AdcampaigngroupinsightsBreakdownsEnumParamCrmUltAdvertiserID                        AdcampaigngroupinsightsBreakdownsEnumParam = "crm_ult_advertiser_id"
	AdcampaigngroupinsightsBreakdownsEnumParamDescriptionAsset                          AdcampaigngroupinsightsBreakdownsEnumParam = "description_asset"
	AdcampaigngroupinsightsBreakdownsEnumParamDevicePlatform                            AdcampaigngroupinsightsBreakdownsEnumParam = "device_platform"
	AdcampaigngroupinsightsBreakdownsEnumParamDma                                       AdcampaigngroupinsightsBreakdownsEnumParam = "dma"
	AdcampaigngroupinsightsBreakdownsEnumParamExistingPostID                            AdcampaigngroupinsightsBreakdownsEnumParam = "existing_post_id"
	AdcampaigngroupinsightsBreakdownsEnumParamFidelityType                              AdcampaigngroupinsightsBreakdownsEnumParam = "fidelity_type"
	AdcampaigngroupinsightsBreakdownsEnumParamFlexibleFormatAssetType                   AdcampaigngroupinsightsBreakdownsEnumParam = "flexible_format_asset_type"
	AdcampaigngroupinsightsBreakdownsEnumParamFrequencyValue                            AdcampaigngroupinsightsBreakdownsEnumParam = "frequency_value"
	AdcampaigngroupinsightsBreakdownsEnumParamGenAiAssetType                            AdcampaigngroupinsightsBreakdownsEnumParam = "gen_ai_asset_type"
	AdcampaigngroupinsightsBreakdownsEnumParamGender                                    AdcampaigngroupinsightsBreakdownsEnumParam = "gender"
	AdcampaigngroupinsightsBreakdownsEnumParamHourlyStatsAggregatedByAdvertiserTimeZone AdcampaigngroupinsightsBreakdownsEnumParam = "hourly_stats_aggregated_by_advertiser_time_zone"
	AdcampaigngroupinsightsBreakdownsEnumParamHourlyStatsAggregatedByAudienceTimeZone   AdcampaigngroupinsightsBreakdownsEnumParam = "hourly_stats_aggregated_by_audience_time_zone"
	AdcampaigngroupinsightsBreakdownsEnumParamHsid                                      AdcampaigngroupinsightsBreakdownsEnumParam = "hsid"
	AdcampaigngroupinsightsBreakdownsEnumParamImageAsset                                AdcampaigngroupinsightsBreakdownsEnumParam = "image_asset"
	AdcampaigngroupinsightsBreakdownsEnumParamImpressionDevice                          AdcampaigngroupinsightsBreakdownsEnumParam = "impression_device"
	AdcampaigngroupinsightsBreakdownsEnumParamImpressionViewTimeAdvertiserHourV2        AdcampaigngroupinsightsBreakdownsEnumParam = "impression_view_time_advertiser_hour_v2"
	AdcampaigngroupinsightsBreakdownsEnumParamInstagramAdsFollowType                    AdcampaigngroupinsightsBreakdownsEnumParam = "instagram_ads_follow_type"
	AdcampaigngroupinsightsBreakdownsEnumParamInstagramAdsInstagramMediaProductType     AdcampaigngroupinsightsBreakdownsEnumParam = "instagram_ads_instagram_media_product_type"
	AdcampaigngroupinsightsBreakdownsEnumParamInstagramAdsTimeSinceCreationBucket       AdcampaigngroupinsightsBreakdownsEnumParam = "instagram_ads_time_since_creation_bucket"
	AdcampaigngroupinsightsBreakdownsEnumParamInternalCampaignID                        AdcampaigngroupinsightsBreakdownsEnumParam = "internal_campaign_id"
	AdcampaigngroupinsightsBreakdownsEnumParamIsAutoAdvance                             AdcampaigngroupinsightsBreakdownsEnumParam = "is_auto_advance"
	AdcampaigngroupinsightsBreakdownsEnumParamIsConversionIDModeled                     AdcampaigngroupinsightsBreakdownsEnumParam = "is_conversion_id_modeled"
	AdcampaigngroupinsightsBreakdownsEnumParamIsRenderedAsDelayedSkipAd                 AdcampaigngroupinsightsBreakdownsEnumParam = "is_rendered_as_delayed_skip_ad"
	AdcampaigngroupinsightsBreakdownsEnumParamLandingDestination                        AdcampaigngroupinsightsBreakdownsEnumParam = "landing_destination"
	AdcampaigngroupinsightsBreakdownsEnumParamLinkURLAsset                              AdcampaigngroupinsightsBreakdownsEnumParam = "link_url_asset"
	AdcampaigngroupinsightsBreakdownsEnumParamMarketingMessagesBtnName                  AdcampaigngroupinsightsBreakdownsEnumParam = "marketing_messages_btn_name"
	AdcampaigngroupinsightsBreakdownsEnumParamMdsaLandingDestination                    AdcampaigngroupinsightsBreakdownsEnumParam = "mdsa_landing_destination"
	AdcampaigngroupinsightsBreakdownsEnumParamMediaAssetURL                             AdcampaigngroupinsightsBreakdownsEnumParam = "media_asset_url"
	AdcampaigngroupinsightsBreakdownsEnumParamMediaCreator                              AdcampaigngroupinsightsBreakdownsEnumParam = "media_creator"
	AdcampaigngroupinsightsBreakdownsEnumParamMediaDestinationURL                       AdcampaigngroupinsightsBreakdownsEnumParam = "media_destination_url"
	AdcampaigngroupinsightsBreakdownsEnumParamMediaFormat                               AdcampaigngroupinsightsBreakdownsEnumParam = "media_format"
	AdcampaigngroupinsightsBreakdownsEnumParamMediaOriginURL                            AdcampaigngroupinsightsBreakdownsEnumParam = "media_origin_url"
	AdcampaigngroupinsightsBreakdownsEnumParamMediaTextContent                          AdcampaigngroupinsightsBreakdownsEnumParam = "media_text_content"
	AdcampaigngroupinsightsBreakdownsEnumParamMediaType                                 AdcampaigngroupinsightsBreakdownsEnumParam = "media_type"
	AdcampaigngroupinsightsBreakdownsEnumParamMmm                                       AdcampaigngroupinsightsBreakdownsEnumParam = "mmm"
	AdcampaigngroupinsightsBreakdownsEnumParamOverlapSegment                            AdcampaigngroupinsightsBreakdownsEnumParam = "overlap_segment"
	AdcampaigngroupinsightsBreakdownsEnumParamPaCreatorIgHandle                         AdcampaigngroupinsightsBreakdownsEnumParam = "pa_creator_ig_handle"
	AdcampaigngroupinsightsBreakdownsEnumParamPlacePageID                               AdcampaigngroupinsightsBreakdownsEnumParam = "place_page_id"
	AdcampaigngroupinsightsBreakdownsEnumParamPlatformPosition                          AdcampaigngroupinsightsBreakdownsEnumParam = "platform_position"
	AdcampaigngroupinsightsBreakdownsEnumParamPostbackSequenceIndex                     AdcampaigngroupinsightsBreakdownsEnumParam = "postback_sequence_index"
	AdcampaigngroupinsightsBreakdownsEnumParamProductBrandBreakdown                     AdcampaigngroupinsightsBreakdownsEnumParam = "product_brand_breakdown"
	AdcampaigngroupinsightsBreakdownsEnumParamProductCategoryBreakdown                  AdcampaigngroupinsightsBreakdownsEnumParam = "product_category_breakdown"
	AdcampaigngroupinsightsBreakdownsEnumParamProductCustomLabelX0Breakdown             AdcampaigngroupinsightsBreakdownsEnumParam = "product_custom_label_0_breakdown"
	AdcampaigngroupinsightsBreakdownsEnumParamProductCustomLabelX1Breakdown             AdcampaigngroupinsightsBreakdownsEnumParam = "product_custom_label_1_breakdown"
	AdcampaigngroupinsightsBreakdownsEnumParamProductCustomLabelX2Breakdown             AdcampaigngroupinsightsBreakdownsEnumParam = "product_custom_label_2_breakdown"
	AdcampaigngroupinsightsBreakdownsEnumParamProductCustomLabelX3Breakdown             AdcampaigngroupinsightsBreakdownsEnumParam = "product_custom_label_3_breakdown"
	AdcampaigngroupinsightsBreakdownsEnumParamProductCustomLabelX4Breakdown             AdcampaigngroupinsightsBreakdownsEnumParam = "product_custom_label_4_breakdown"
	AdcampaigngroupinsightsBreakdownsEnumParamProductGroupContentIDBreakdown            AdcampaigngroupinsightsBreakdownsEnumParam = "product_group_content_id_breakdown"
	AdcampaigngroupinsightsBreakdownsEnumParamProductID                                 AdcampaigngroupinsightsBreakdownsEnumParam = "product_id"
	AdcampaigngroupinsightsBreakdownsEnumParamPublisherPlatform                         AdcampaigngroupinsightsBreakdownsEnumParam = "publisher_platform"
	AdcampaigngroupinsightsBreakdownsEnumParamRedownload                                AdcampaigngroupinsightsBreakdownsEnumParam = "redownload"
	AdcampaigngroupinsightsBreakdownsEnumParamReelsTrendingTopic                        AdcampaigngroupinsightsBreakdownsEnumParam = "reels_trending_topic"
	AdcampaigngroupinsightsBreakdownsEnumParamRegion                                    AdcampaigngroupinsightsBreakdownsEnumParam = "region"
	AdcampaigngroupinsightsBreakdownsEnumParamRtaUgcTopic                               AdcampaigngroupinsightsBreakdownsEnumParam = "rta_ugc_topic"
	AdcampaigngroupinsightsBreakdownsEnumParamRuleSetID                                 AdcampaigngroupinsightsBreakdownsEnumParam = "rule_set_id"
	AdcampaigngroupinsightsBreakdownsEnumParamRuleSetName                               AdcampaigngroupinsightsBreakdownsEnumParam = "rule_set_name"
	AdcampaigngroupinsightsBreakdownsEnumParamSignalSourceBucket                        AdcampaigngroupinsightsBreakdownsEnumParam = "signal_source_bucket"
	AdcampaigngroupinsightsBreakdownsEnumParamSkanCampaignID                            AdcampaigngroupinsightsBreakdownsEnumParam = "skan_campaign_id"
	AdcampaigngroupinsightsBreakdownsEnumParamSkanConversionID                          AdcampaigngroupinsightsBreakdownsEnumParam = "skan_conversion_id"
	AdcampaigngroupinsightsBreakdownsEnumParamSkanVersion                               AdcampaigngroupinsightsBreakdownsEnumParam = "skan_version"
	AdcampaigngroupinsightsBreakdownsEnumParamSotAttributionModelType                   AdcampaigngroupinsightsBreakdownsEnumParam = "sot_attribution_model_type"
	AdcampaigngroupinsightsBreakdownsEnumParamSotAttributionWindow                      AdcampaigngroupinsightsBreakdownsEnumParam = "sot_attribution_window"
	AdcampaigngroupinsightsBreakdownsEnumParamSotChannel                                AdcampaigngroupinsightsBreakdownsEnumParam = "sot_channel"
	AdcampaigngroupinsightsBreakdownsEnumParamSotEventType                              AdcampaigngroupinsightsBreakdownsEnumParam = "sot_event_type"
	AdcampaigngroupinsightsBreakdownsEnumParamSotSource                                 AdcampaigngroupinsightsBreakdownsEnumParam = "sot_source"
	AdcampaigngroupinsightsBreakdownsEnumParamStandardEventContentType                  AdcampaigngroupinsightsBreakdownsEnumParam = "standard_event_content_type"
	AdcampaigngroupinsightsBreakdownsEnumParamTitleAsset                                AdcampaigngroupinsightsBreakdownsEnumParam = "title_asset"
	AdcampaigngroupinsightsBreakdownsEnumParamUserPersonaID                             AdcampaigngroupinsightsBreakdownsEnumParam = "user_persona_id"
	AdcampaigngroupinsightsBreakdownsEnumParamUserPersonaName                           AdcampaigngroupinsightsBreakdownsEnumParam = "user_persona_name"
	AdcampaigngroupinsightsBreakdownsEnumParamVideoAsset                                AdcampaigngroupinsightsBreakdownsEnumParam = "video_asset"
	AdcampaigngroupinsightsBreakdownsEnumParamZip                                       AdcampaigngroupinsightsBreakdownsEnumParam = "zip"
)

func (value AdcampaigngroupinsightsBreakdownsEnumParam) String() string {
	return string(value)
}
