package enums

type AdcampaigninsightsBreakdownsEnumParam string

const (
	AdcampaigninsightsBreakdownsEnumParamAdExtensionDomain                         AdcampaigninsightsBreakdownsEnumParam = "ad_extension_domain"
	AdcampaigninsightsBreakdownsEnumParamAdExtensionURL                            AdcampaigninsightsBreakdownsEnumParam = "ad_extension_url"
	AdcampaigninsightsBreakdownsEnumParamAdFormatAsset                             AdcampaigninsightsBreakdownsEnumParam = "ad_format_asset"
	AdcampaigninsightsBreakdownsEnumParamAge                                       AdcampaigninsightsBreakdownsEnumParam = "age"
	AdcampaigninsightsBreakdownsEnumParamAppID                                     AdcampaigninsightsBreakdownsEnumParam = "app_id"
	AdcampaigninsightsBreakdownsEnumParamBodyAsset                                 AdcampaigninsightsBreakdownsEnumParam = "body_asset"
	AdcampaigninsightsBreakdownsEnumParamBreakdownAdObjective                      AdcampaigninsightsBreakdownsEnumParam = "breakdown_ad_objective"
	AdcampaigninsightsBreakdownsEnumParamBreakdownReportingAdID                    AdcampaigninsightsBreakdownsEnumParam = "breakdown_reporting_ad_id"
	AdcampaigninsightsBreakdownsEnumParamCallToActionAsset                         AdcampaigninsightsBreakdownsEnumParam = "call_to_action_asset"
	AdcampaigninsightsBreakdownsEnumParamCoarseConversionValue                     AdcampaigninsightsBreakdownsEnumParam = "coarse_conversion_value"
	AdcampaigninsightsBreakdownsEnumParamComscoreMarket                            AdcampaigninsightsBreakdownsEnumParam = "comscore_market"
	AdcampaigninsightsBreakdownsEnumParamConversionDestination                     AdcampaigninsightsBreakdownsEnumParam = "conversion_destination"
	AdcampaigninsightsBreakdownsEnumParamCountry                                   AdcampaigninsightsBreakdownsEnumParam = "country"
	AdcampaigninsightsBreakdownsEnumParamCreativeAutomationAssetID                 AdcampaigninsightsBreakdownsEnumParam = "creative_automation_asset_id"
	AdcampaigninsightsBreakdownsEnumParamCreativeRelaxationAssetType               AdcampaigninsightsBreakdownsEnumParam = "creative_relaxation_asset_type"
	AdcampaigninsightsBreakdownsEnumParamCrmAdvertiserL12TerritoryIds              AdcampaigninsightsBreakdownsEnumParam = "crm_advertiser_l12_territory_ids"
	AdcampaigninsightsBreakdownsEnumParamCrmAdvertiserSubverticalID                AdcampaigninsightsBreakdownsEnumParam = "crm_advertiser_subvertical_id"
	AdcampaigninsightsBreakdownsEnumParamCrmAdvertiserVerticalID                   AdcampaigninsightsBreakdownsEnumParam = "crm_advertiser_vertical_id"
	AdcampaigninsightsBreakdownsEnumParamCrmUltAdvertiserID                        AdcampaigninsightsBreakdownsEnumParam = "crm_ult_advertiser_id"
	AdcampaigninsightsBreakdownsEnumParamDescriptionAsset                          AdcampaigninsightsBreakdownsEnumParam = "description_asset"
	AdcampaigninsightsBreakdownsEnumParamDevicePlatform                            AdcampaigninsightsBreakdownsEnumParam = "device_platform"
	AdcampaigninsightsBreakdownsEnumParamDma                                       AdcampaigninsightsBreakdownsEnumParam = "dma"
	AdcampaigninsightsBreakdownsEnumParamExistingPostID                            AdcampaigninsightsBreakdownsEnumParam = "existing_post_id"
	AdcampaigninsightsBreakdownsEnumParamFidelityType                              AdcampaigninsightsBreakdownsEnumParam = "fidelity_type"
	AdcampaigninsightsBreakdownsEnumParamFlexibleFormatAssetType                   AdcampaigninsightsBreakdownsEnumParam = "flexible_format_asset_type"
	AdcampaigninsightsBreakdownsEnumParamFrequencyValue                            AdcampaigninsightsBreakdownsEnumParam = "frequency_value"
	AdcampaigninsightsBreakdownsEnumParamGenAiAssetType                            AdcampaigninsightsBreakdownsEnumParam = "gen_ai_asset_type"
	AdcampaigninsightsBreakdownsEnumParamGender                                    AdcampaigninsightsBreakdownsEnumParam = "gender"
	AdcampaigninsightsBreakdownsEnumParamHourlyStatsAggregatedByAdvertiserTimeZone AdcampaigninsightsBreakdownsEnumParam = "hourly_stats_aggregated_by_advertiser_time_zone"
	AdcampaigninsightsBreakdownsEnumParamHourlyStatsAggregatedByAudienceTimeZone   AdcampaigninsightsBreakdownsEnumParam = "hourly_stats_aggregated_by_audience_time_zone"
	AdcampaigninsightsBreakdownsEnumParamHsid                                      AdcampaigninsightsBreakdownsEnumParam = "hsid"
	AdcampaigninsightsBreakdownsEnumParamImageAsset                                AdcampaigninsightsBreakdownsEnumParam = "image_asset"
	AdcampaigninsightsBreakdownsEnumParamImpressionDevice                          AdcampaigninsightsBreakdownsEnumParam = "impression_device"
	AdcampaigninsightsBreakdownsEnumParamImpressionViewTimeAdvertiserHourV2        AdcampaigninsightsBreakdownsEnumParam = "impression_view_time_advertiser_hour_v2"
	AdcampaigninsightsBreakdownsEnumParamInstagramAdsFollowType                    AdcampaigninsightsBreakdownsEnumParam = "instagram_ads_follow_type"
	AdcampaigninsightsBreakdownsEnumParamInstagramAdsInstagramMediaProductType     AdcampaigninsightsBreakdownsEnumParam = "instagram_ads_instagram_media_product_type"
	AdcampaigninsightsBreakdownsEnumParamInstagramAdsTimeSinceCreationBucket       AdcampaigninsightsBreakdownsEnumParam = "instagram_ads_time_since_creation_bucket"
	AdcampaigninsightsBreakdownsEnumParamInternalCampaignID                        AdcampaigninsightsBreakdownsEnumParam = "internal_campaign_id"
	AdcampaigninsightsBreakdownsEnumParamIsAutoAdvance                             AdcampaigninsightsBreakdownsEnumParam = "is_auto_advance"
	AdcampaigninsightsBreakdownsEnumParamIsConversionIDModeled                     AdcampaigninsightsBreakdownsEnumParam = "is_conversion_id_modeled"
	AdcampaigninsightsBreakdownsEnumParamIsRenderedAsDelayedSkipAd                 AdcampaigninsightsBreakdownsEnumParam = "is_rendered_as_delayed_skip_ad"
	AdcampaigninsightsBreakdownsEnumParamLandingDestination                        AdcampaigninsightsBreakdownsEnumParam = "landing_destination"
	AdcampaigninsightsBreakdownsEnumParamLinkURLAsset                              AdcampaigninsightsBreakdownsEnumParam = "link_url_asset"
	AdcampaigninsightsBreakdownsEnumParamMarketingMessagesBtnName                  AdcampaigninsightsBreakdownsEnumParam = "marketing_messages_btn_name"
	AdcampaigninsightsBreakdownsEnumParamMdsaLandingDestination                    AdcampaigninsightsBreakdownsEnumParam = "mdsa_landing_destination"
	AdcampaigninsightsBreakdownsEnumParamMediaAssetURL                             AdcampaigninsightsBreakdownsEnumParam = "media_asset_url"
	AdcampaigninsightsBreakdownsEnumParamMediaCreator                              AdcampaigninsightsBreakdownsEnumParam = "media_creator"
	AdcampaigninsightsBreakdownsEnumParamMediaDestinationURL                       AdcampaigninsightsBreakdownsEnumParam = "media_destination_url"
	AdcampaigninsightsBreakdownsEnumParamMediaFormat                               AdcampaigninsightsBreakdownsEnumParam = "media_format"
	AdcampaigninsightsBreakdownsEnumParamMediaOriginURL                            AdcampaigninsightsBreakdownsEnumParam = "media_origin_url"
	AdcampaigninsightsBreakdownsEnumParamMediaTextContent                          AdcampaigninsightsBreakdownsEnumParam = "media_text_content"
	AdcampaigninsightsBreakdownsEnumParamMediaType                                 AdcampaigninsightsBreakdownsEnumParam = "media_type"
	AdcampaigninsightsBreakdownsEnumParamMmm                                       AdcampaigninsightsBreakdownsEnumParam = "mmm"
	AdcampaigninsightsBreakdownsEnumParamOverlapSegment                            AdcampaigninsightsBreakdownsEnumParam = "overlap_segment"
	AdcampaigninsightsBreakdownsEnumParamPaCreatorIgHandle                         AdcampaigninsightsBreakdownsEnumParam = "pa_creator_ig_handle"
	AdcampaigninsightsBreakdownsEnumParamPlacePageID                               AdcampaigninsightsBreakdownsEnumParam = "place_page_id"
	AdcampaigninsightsBreakdownsEnumParamPlatformPosition                          AdcampaigninsightsBreakdownsEnumParam = "platform_position"
	AdcampaigninsightsBreakdownsEnumParamPostbackSequenceIndex                     AdcampaigninsightsBreakdownsEnumParam = "postback_sequence_index"
	AdcampaigninsightsBreakdownsEnumParamProductBrandBreakdown                     AdcampaigninsightsBreakdownsEnumParam = "product_brand_breakdown"
	AdcampaigninsightsBreakdownsEnumParamProductCategoryBreakdown                  AdcampaigninsightsBreakdownsEnumParam = "product_category_breakdown"
	AdcampaigninsightsBreakdownsEnumParamProductCustomLabelX0Breakdown             AdcampaigninsightsBreakdownsEnumParam = "product_custom_label_0_breakdown"
	AdcampaigninsightsBreakdownsEnumParamProductCustomLabelX1Breakdown             AdcampaigninsightsBreakdownsEnumParam = "product_custom_label_1_breakdown"
	AdcampaigninsightsBreakdownsEnumParamProductCustomLabelX2Breakdown             AdcampaigninsightsBreakdownsEnumParam = "product_custom_label_2_breakdown"
	AdcampaigninsightsBreakdownsEnumParamProductCustomLabelX3Breakdown             AdcampaigninsightsBreakdownsEnumParam = "product_custom_label_3_breakdown"
	AdcampaigninsightsBreakdownsEnumParamProductCustomLabelX4Breakdown             AdcampaigninsightsBreakdownsEnumParam = "product_custom_label_4_breakdown"
	AdcampaigninsightsBreakdownsEnumParamProductGroupContentIDBreakdown            AdcampaigninsightsBreakdownsEnumParam = "product_group_content_id_breakdown"
	AdcampaigninsightsBreakdownsEnumParamProductID                                 AdcampaigninsightsBreakdownsEnumParam = "product_id"
	AdcampaigninsightsBreakdownsEnumParamPublisherPlatform                         AdcampaigninsightsBreakdownsEnumParam = "publisher_platform"
	AdcampaigninsightsBreakdownsEnumParamRedownload                                AdcampaigninsightsBreakdownsEnumParam = "redownload"
	AdcampaigninsightsBreakdownsEnumParamReelsTrendingTopic                        AdcampaigninsightsBreakdownsEnumParam = "reels_trending_topic"
	AdcampaigninsightsBreakdownsEnumParamRegion                                    AdcampaigninsightsBreakdownsEnumParam = "region"
	AdcampaigninsightsBreakdownsEnumParamRtaUgcTopic                               AdcampaigninsightsBreakdownsEnumParam = "rta_ugc_topic"
	AdcampaigninsightsBreakdownsEnumParamRuleSetID                                 AdcampaigninsightsBreakdownsEnumParam = "rule_set_id"
	AdcampaigninsightsBreakdownsEnumParamRuleSetName                               AdcampaigninsightsBreakdownsEnumParam = "rule_set_name"
	AdcampaigninsightsBreakdownsEnumParamSignalSourceBucket                        AdcampaigninsightsBreakdownsEnumParam = "signal_source_bucket"
	AdcampaigninsightsBreakdownsEnumParamSkanCampaignID                            AdcampaigninsightsBreakdownsEnumParam = "skan_campaign_id"
	AdcampaigninsightsBreakdownsEnumParamSkanConversionID                          AdcampaigninsightsBreakdownsEnumParam = "skan_conversion_id"
	AdcampaigninsightsBreakdownsEnumParamSkanVersion                               AdcampaigninsightsBreakdownsEnumParam = "skan_version"
	AdcampaigninsightsBreakdownsEnumParamSotAttributionModelType                   AdcampaigninsightsBreakdownsEnumParam = "sot_attribution_model_type"
	AdcampaigninsightsBreakdownsEnumParamSotAttributionWindow                      AdcampaigninsightsBreakdownsEnumParam = "sot_attribution_window"
	AdcampaigninsightsBreakdownsEnumParamSotChannel                                AdcampaigninsightsBreakdownsEnumParam = "sot_channel"
	AdcampaigninsightsBreakdownsEnumParamSotEventType                              AdcampaigninsightsBreakdownsEnumParam = "sot_event_type"
	AdcampaigninsightsBreakdownsEnumParamSotSource                                 AdcampaigninsightsBreakdownsEnumParam = "sot_source"
	AdcampaigninsightsBreakdownsEnumParamStandardEventContentType                  AdcampaigninsightsBreakdownsEnumParam = "standard_event_content_type"
	AdcampaigninsightsBreakdownsEnumParamTitleAsset                                AdcampaigninsightsBreakdownsEnumParam = "title_asset"
	AdcampaigninsightsBreakdownsEnumParamUserPersonaID                             AdcampaigninsightsBreakdownsEnumParam = "user_persona_id"
	AdcampaigninsightsBreakdownsEnumParamUserPersonaName                           AdcampaigninsightsBreakdownsEnumParam = "user_persona_name"
	AdcampaigninsightsBreakdownsEnumParamVideoAsset                                AdcampaigninsightsBreakdownsEnumParam = "video_asset"
	AdcampaigninsightsBreakdownsEnumParamZip                                       AdcampaigninsightsBreakdownsEnumParam = "zip"
)

func (value AdcampaigninsightsBreakdownsEnumParam) String() string {
	return string(value)
}
