package enums

type AdcreativepreviewsAdFormatEnumParam string

const (
	AdcreativepreviewsAdFormatEnumParamAudienceNetworkInstreamVideo        AdcreativepreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_INSTREAM_VIDEO"
	AdcreativepreviewsAdFormatEnumParamAudienceNetworkInstreamVideoMobile  AdcreativepreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_INSTREAM_VIDEO_MOBILE"
	AdcreativepreviewsAdFormatEnumParamAudienceNetworkOutstreamVideo       AdcreativepreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_OUTSTREAM_VIDEO"
	AdcreativepreviewsAdFormatEnumParamAudienceNetworkRewardedVideo        AdcreativepreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_REWARDED_VIDEO"
	AdcreativepreviewsAdFormatEnumParamBizDiscoFeedMobile                  AdcreativepreviewsAdFormatEnumParam = "BIZ_DISCO_FEED_MOBILE"
	AdcreativepreviewsAdFormatEnumParamDesktopFeedStandard                 AdcreativepreviewsAdFormatEnumParam = "DESKTOP_FEED_STANDARD"
	AdcreativepreviewsAdFormatEnumParamFacebookIfuReelsMobile              AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_IFU_REELS_MOBILE"
	AdcreativepreviewsAdFormatEnumParamFacebookProfileFeedDesktop          AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_PROFILE_FEED_DESKTOP"
	AdcreativepreviewsAdFormatEnumParamFacebookProfileFeedMobile           AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_PROFILE_FEED_MOBILE"
	AdcreativepreviewsAdFormatEnumParamFacebookProfileReelsMobile          AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_PROFILE_REELS_MOBILE"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsBanner                 AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsBannerDesktop          AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_DESKTOP"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsBannerFeedAndroid      AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FEED_ANDROID"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsBannerFeedAndroidLarge AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FEED_ANDROID_LARGE"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsBannerFullscreenIos    AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FULLSCREEN_IOS"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsBannerFullscreenMobile AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FULLSCREEN_MOBILE"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsMobile                 AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_MOBILE"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsPostloop               AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_POSTLOOP"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsPostloopFeed           AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_POSTLOOP_FEED"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsSimilarProductsMobile  AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_SIMILAR_PRODUCTS_MOBILE"
	AdcreativepreviewsAdFormatEnumParamFacebookReelsSticker                AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_REELS_STICKER"
	AdcreativepreviewsAdFormatEnumParamFacebookStoryMobile                 AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_STORY_MOBILE"
	AdcreativepreviewsAdFormatEnumParamFacebookStoryStickerMobile          AdcreativepreviewsAdFormatEnumParam = "FACEBOOK_STORY_STICKER_MOBILE"
	AdcreativepreviewsAdFormatEnumParamInstagramExploreContextual          AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_EXPLORE_CONTEXTUAL"
	AdcreativepreviewsAdFormatEnumParamInstagramExploreGridHome            AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_EXPLORE_GRID_HOME"
	AdcreativepreviewsAdFormatEnumParamInstagramExploreImmersive           AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_EXPLORE_IMMERSIVE"
	AdcreativepreviewsAdFormatEnumParamInstagramFeedWeb                    AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_FEED_WEB"
	AdcreativepreviewsAdFormatEnumParamInstagramFeedWebMSite               AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_FEED_WEB_M_SITE"
	AdcreativepreviewsAdFormatEnumParamInstagramLeadGenMultiSubmitAds      AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_LEAD_GEN_MULTI_SUBMIT_ADS"
	AdcreativepreviewsAdFormatEnumParamInstagramProfileFeed                AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_PROFILE_FEED"
	AdcreativepreviewsAdFormatEnumParamInstagramProfileReels               AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_PROFILE_REELS"
	AdcreativepreviewsAdFormatEnumParamInstagramReels                      AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_REELS"
	AdcreativepreviewsAdFormatEnumParamInstagramReelsOverlay               AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_REELS_OVERLAY"
	AdcreativepreviewsAdFormatEnumParamInstagramReelsWeb                   AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_REELS_WEB"
	AdcreativepreviewsAdFormatEnumParamInstagramReelsWebMSite              AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_REELS_WEB_M_SITE"
	AdcreativepreviewsAdFormatEnumParamInstagramSearchChain                AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_SEARCH_CHAIN"
	AdcreativepreviewsAdFormatEnumParamInstagramSearchGrid                 AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_SEARCH_GRID"
	AdcreativepreviewsAdFormatEnumParamInstagramStandard                   AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_STANDARD"
	AdcreativepreviewsAdFormatEnumParamInstagramStory                      AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_STORY"
	AdcreativepreviewsAdFormatEnumParamInstagramStoryEffectTray            AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_STORY_EFFECT_TRAY"
	AdcreativepreviewsAdFormatEnumParamInstagramStoryWeb                   AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_STORY_WEB"
	AdcreativepreviewsAdFormatEnumParamInstagramStoryWebMSite              AdcreativepreviewsAdFormatEnumParam = "INSTAGRAM_STORY_WEB_M_SITE"
	AdcreativepreviewsAdFormatEnumParamInstantArticleRecirculationAd       AdcreativepreviewsAdFormatEnumParam = "INSTANT_ARTICLE_RECIRCULATION_AD"
	AdcreativepreviewsAdFormatEnumParamInstantArticleStandard              AdcreativepreviewsAdFormatEnumParam = "INSTANT_ARTICLE_STANDARD"
	AdcreativepreviewsAdFormatEnumParamInstreamBannerDesktop               AdcreativepreviewsAdFormatEnumParam = "INSTREAM_BANNER_DESKTOP"
	AdcreativepreviewsAdFormatEnumParamInstreamBannerFeedIos               AdcreativepreviewsAdFormatEnumParam = "INSTREAM_BANNER_FEED_IOS"
	AdcreativepreviewsAdFormatEnumParamInstreamBannerFullscreenIos         AdcreativepreviewsAdFormatEnumParam = "INSTREAM_BANNER_FULLSCREEN_IOS"
	AdcreativepreviewsAdFormatEnumParamInstreamBannerFullscreenMobile      AdcreativepreviewsAdFormatEnumParam = "INSTREAM_BANNER_FULLSCREEN_MOBILE"
	AdcreativepreviewsAdFormatEnumParamInstreamBannerImmersiveMobile       AdcreativepreviewsAdFormatEnumParam = "INSTREAM_BANNER_IMMERSIVE_MOBILE"
	AdcreativepreviewsAdFormatEnumParamInstreamBannerMobile                AdcreativepreviewsAdFormatEnumParam = "INSTREAM_BANNER_MOBILE"
	AdcreativepreviewsAdFormatEnumParamInstreamVideoDesktop                AdcreativepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_DESKTOP"
	AdcreativepreviewsAdFormatEnumParamInstreamVideoFullscreenIos          AdcreativepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_FULLSCREEN_IOS"
	AdcreativepreviewsAdFormatEnumParamInstreamVideoFullscreenMobile       AdcreativepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_FULLSCREEN_MOBILE"
	AdcreativepreviewsAdFormatEnumParamInstreamVideoImage                  AdcreativepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_IMAGE"
	AdcreativepreviewsAdFormatEnumParamInstreamVideoImmersiveMobile        AdcreativepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_IMMERSIVE_MOBILE"
	AdcreativepreviewsAdFormatEnumParamInstreamVideoMobile                 AdcreativepreviewsAdFormatEnumParam = "INSTREAM_VIDEO_MOBILE"
	AdcreativepreviewsAdFormatEnumParamJobBrowserDesktop                   AdcreativepreviewsAdFormatEnumParam = "JOB_BROWSER_DESKTOP"
	AdcreativepreviewsAdFormatEnumParamJobBrowserMobile                    AdcreativepreviewsAdFormatEnumParam = "JOB_BROWSER_MOBILE"
	AdcreativepreviewsAdFormatEnumParamMarketplaceMobile                   AdcreativepreviewsAdFormatEnumParam = "MARKETPLACE_MOBILE"
	AdcreativepreviewsAdFormatEnumParamMessengerMobileInboxMedia           AdcreativepreviewsAdFormatEnumParam = "MESSENGER_MOBILE_INBOX_MEDIA"
	AdcreativepreviewsAdFormatEnumParamMessengerMobileStoryMedia           AdcreativepreviewsAdFormatEnumParam = "MESSENGER_MOBILE_STORY_MEDIA"
	AdcreativepreviewsAdFormatEnumParamMobileBanner                        AdcreativepreviewsAdFormatEnumParam = "MOBILE_BANNER"
	AdcreativepreviewsAdFormatEnumParamMobileFeedBasic                     AdcreativepreviewsAdFormatEnumParam = "MOBILE_FEED_BASIC"
	AdcreativepreviewsAdFormatEnumParamMobileFeedStandard                  AdcreativepreviewsAdFormatEnumParam = "MOBILE_FEED_STANDARD"
	AdcreativepreviewsAdFormatEnumParamMobileFullwidth                     AdcreativepreviewsAdFormatEnumParam = "MOBILE_FULLWIDTH"
	AdcreativepreviewsAdFormatEnumParamMobileInterstitial                  AdcreativepreviewsAdFormatEnumParam = "MOBILE_INTERSTITIAL"
	AdcreativepreviewsAdFormatEnumParamMobileMediumRectangle               AdcreativepreviewsAdFormatEnumParam = "MOBILE_MEDIUM_RECTANGLE"
	AdcreativepreviewsAdFormatEnumParamMobileNative                        AdcreativepreviewsAdFormatEnumParam = "MOBILE_NATIVE"
	AdcreativepreviewsAdFormatEnumParamRightColumnStandard                 AdcreativepreviewsAdFormatEnumParam = "RIGHT_COLUMN_STANDARD"
	AdcreativepreviewsAdFormatEnumParamSuggestedVideoDesktop               AdcreativepreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_DESKTOP"
	AdcreativepreviewsAdFormatEnumParamSuggestedVideoFullscreenMobile      AdcreativepreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_FULLSCREEN_MOBILE"
	AdcreativepreviewsAdFormatEnumParamSuggestedVideoImmersiveMobile       AdcreativepreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_IMMERSIVE_MOBILE"
	AdcreativepreviewsAdFormatEnumParamSuggestedVideoMobile                AdcreativepreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_MOBILE"
	AdcreativepreviewsAdFormatEnumParamWatchFeedHome                       AdcreativepreviewsAdFormatEnumParam = "WATCH_FEED_HOME"
	AdcreativepreviewsAdFormatEnumParamWatchFeedMobile                     AdcreativepreviewsAdFormatEnumParam = "WATCH_FEED_MOBILE"
	AdcreativepreviewsAdFormatEnumParamWhatsappStatusMedia                 AdcreativepreviewsAdFormatEnumParam = "WHATSAPP_STATUS_MEDIA"
)

func (value AdcreativepreviewsAdFormatEnumParam) String() string {
	return string(value)
}
