package enums

type AdgroupinsightsBreakdownsEnumParam string

const (
	AdgroupinsightsBreakdownsEnumParamAdExtensionDomain                         AdgroupinsightsBreakdownsEnumParam = "ad_extension_domain"
	AdgroupinsightsBreakdownsEnumParamAdExtensionURL                            AdgroupinsightsBreakdownsEnumParam = "ad_extension_url"
	AdgroupinsightsBreakdownsEnumParamAdFormatAsset                             AdgroupinsightsBreakdownsEnumParam = "ad_format_asset"
	AdgroupinsightsBreakdownsEnumParamAge                                       AdgroupinsightsBreakdownsEnumParam = "age"
	AdgroupinsightsBreakdownsEnumParamAppID                                     AdgroupinsightsBreakdownsEnumParam = "app_id"
	AdgroupinsightsBreakdownsEnumParamBodyAsset                                 AdgroupinsightsBreakdownsEnumParam = "body_asset"
	AdgroupinsightsBreakdownsEnumParamBreakdownAdObjective                      AdgroupinsightsBreakdownsEnumParam = "breakdown_ad_objective"
	AdgroupinsightsBreakdownsEnumParamBreakdownReportingAdID                    AdgroupinsightsBreakdownsEnumParam = "breakdown_reporting_ad_id"
	AdgroupinsightsBreakdownsEnumParamCallToActionAsset                         AdgroupinsightsBreakdownsEnumParam = "call_to_action_asset"
	AdgroupinsightsBreakdownsEnumParamCoarseConversionValue                     AdgroupinsightsBreakdownsEnumParam = "coarse_conversion_value"
	AdgroupinsightsBreakdownsEnumParamComscoreMarket                            AdgroupinsightsBreakdownsEnumParam = "comscore_market"
	AdgroupinsightsBreakdownsEnumParamConversionDestination                     AdgroupinsightsBreakdownsEnumParam = "conversion_destination"
	AdgroupinsightsBreakdownsEnumParamCountry                                   AdgroupinsightsBreakdownsEnumParam = "country"
	AdgroupinsightsBreakdownsEnumParamCreativeAutomationAssetID                 AdgroupinsightsBreakdownsEnumParam = "creative_automation_asset_id"
	AdgroupinsightsBreakdownsEnumParamCreativeRelaxationAssetType               AdgroupinsightsBreakdownsEnumParam = "creative_relaxation_asset_type"
	AdgroupinsightsBreakdownsEnumParamCrmAdvertiserL12TerritoryIds              AdgroupinsightsBreakdownsEnumParam = "crm_advertiser_l12_territory_ids"
	AdgroupinsightsBreakdownsEnumParamCrmAdvertiserSubverticalID                AdgroupinsightsBreakdownsEnumParam = "crm_advertiser_subvertical_id"
	AdgroupinsightsBreakdownsEnumParamCrmAdvertiserVerticalID                   AdgroupinsightsBreakdownsEnumParam = "crm_advertiser_vertical_id"
	AdgroupinsightsBreakdownsEnumParamCrmUltAdvertiserID                        AdgroupinsightsBreakdownsEnumParam = "crm_ult_advertiser_id"
	AdgroupinsightsBreakdownsEnumParamDescriptionAsset                          AdgroupinsightsBreakdownsEnumParam = "description_asset"
	AdgroupinsightsBreakdownsEnumParamDevicePlatform                            AdgroupinsightsBreakdownsEnumParam = "device_platform"
	AdgroupinsightsBreakdownsEnumParamDma                                       AdgroupinsightsBreakdownsEnumParam = "dma"
	AdgroupinsightsBreakdownsEnumParamExistingPostID                            AdgroupinsightsBreakdownsEnumParam = "existing_post_id"
	AdgroupinsightsBreakdownsEnumParamFidelityType                              AdgroupinsightsBreakdownsEnumParam = "fidelity_type"
	AdgroupinsightsBreakdownsEnumParamFlexibleFormatAssetType                   AdgroupinsightsBreakdownsEnumParam = "flexible_format_asset_type"
	AdgroupinsightsBreakdownsEnumParamFrequencyValue                            AdgroupinsightsBreakdownsEnumParam = "frequency_value"
	AdgroupinsightsBreakdownsEnumParamGenAiAssetType                            AdgroupinsightsBreakdownsEnumParam = "gen_ai_asset_type"
	AdgroupinsightsBreakdownsEnumParamGender                                    AdgroupinsightsBreakdownsEnumParam = "gender"
	AdgroupinsightsBreakdownsEnumParamHourlyStatsAggregatedByAdvertiserTimeZone AdgroupinsightsBreakdownsEnumParam = "hourly_stats_aggregated_by_advertiser_time_zone"
	AdgroupinsightsBreakdownsEnumParamHourlyStatsAggregatedByAudienceTimeZone   AdgroupinsightsBreakdownsEnumParam = "hourly_stats_aggregated_by_audience_time_zone"
	AdgroupinsightsBreakdownsEnumParamHsid                                      AdgroupinsightsBreakdownsEnumParam = "hsid"
	AdgroupinsightsBreakdownsEnumParamImageAsset                                AdgroupinsightsBreakdownsEnumParam = "image_asset"
	AdgroupinsightsBreakdownsEnumParamImpressionDevice                          AdgroupinsightsBreakdownsEnumParam = "impression_device"
	AdgroupinsightsBreakdownsEnumParamImpressionViewTimeAdvertiserHourV2        AdgroupinsightsBreakdownsEnumParam = "impression_view_time_advertiser_hour_v2"
	AdgroupinsightsBreakdownsEnumParamInstagramAdsFollowType                    AdgroupinsightsBreakdownsEnumParam = "instagram_ads_follow_type"
	AdgroupinsightsBreakdownsEnumParamInstagramAdsInstagramMediaProductType     AdgroupinsightsBreakdownsEnumParam = "instagram_ads_instagram_media_product_type"
	AdgroupinsightsBreakdownsEnumParamInstagramAdsTimeSinceCreationBucket       AdgroupinsightsBreakdownsEnumParam = "instagram_ads_time_since_creation_bucket"
	AdgroupinsightsBreakdownsEnumParamInternalCampaignID                        AdgroupinsightsBreakdownsEnumParam = "internal_campaign_id"
	AdgroupinsightsBreakdownsEnumParamIsAutoAdvance                             AdgroupinsightsBreakdownsEnumParam = "is_auto_advance"
	AdgroupinsightsBreakdownsEnumParamIsConversionIDModeled                     AdgroupinsightsBreakdownsEnumParam = "is_conversion_id_modeled"
	AdgroupinsightsBreakdownsEnumParamIsRenderedAsDelayedSkipAd                 AdgroupinsightsBreakdownsEnumParam = "is_rendered_as_delayed_skip_ad"
	AdgroupinsightsBreakdownsEnumParamLandingDestination                        AdgroupinsightsBreakdownsEnumParam = "landing_destination"
	AdgroupinsightsBreakdownsEnumParamLinkURLAsset                              AdgroupinsightsBreakdownsEnumParam = "link_url_asset"
	AdgroupinsightsBreakdownsEnumParamMarketingMessagesBtnName                  AdgroupinsightsBreakdownsEnumParam = "marketing_messages_btn_name"
	AdgroupinsightsBreakdownsEnumParamMdsaLandingDestination                    AdgroupinsightsBreakdownsEnumParam = "mdsa_landing_destination"
	AdgroupinsightsBreakdownsEnumParamMediaAssetURL                             AdgroupinsightsBreakdownsEnumParam = "media_asset_url"
	AdgroupinsightsBreakdownsEnumParamMediaCreator                              AdgroupinsightsBreakdownsEnumParam = "media_creator"
	AdgroupinsightsBreakdownsEnumParamMediaDestinationURL                       AdgroupinsightsBreakdownsEnumParam = "media_destination_url"
	AdgroupinsightsBreakdownsEnumParamMediaFormat                               AdgroupinsightsBreakdownsEnumParam = "media_format"
	AdgroupinsightsBreakdownsEnumParamMediaOriginURL                            AdgroupinsightsBreakdownsEnumParam = "media_origin_url"
	AdgroupinsightsBreakdownsEnumParamMediaTextContent                          AdgroupinsightsBreakdownsEnumParam = "media_text_content"
	AdgroupinsightsBreakdownsEnumParamMediaType                                 AdgroupinsightsBreakdownsEnumParam = "media_type"
	AdgroupinsightsBreakdownsEnumParamMmm                                       AdgroupinsightsBreakdownsEnumParam = "mmm"
	AdgroupinsightsBreakdownsEnumParamOverlapSegment                            AdgroupinsightsBreakdownsEnumParam = "overlap_segment"
	AdgroupinsightsBreakdownsEnumParamPaCreatorIgHandle                         AdgroupinsightsBreakdownsEnumParam = "pa_creator_ig_handle"
	AdgroupinsightsBreakdownsEnumParamPlacePageID                               AdgroupinsightsBreakdownsEnumParam = "place_page_id"
	AdgroupinsightsBreakdownsEnumParamPlatformPosition                          AdgroupinsightsBreakdownsEnumParam = "platform_position"
	AdgroupinsightsBreakdownsEnumParamPostbackSequenceIndex                     AdgroupinsightsBreakdownsEnumParam = "postback_sequence_index"
	AdgroupinsightsBreakdownsEnumParamProductBrandBreakdown                     AdgroupinsightsBreakdownsEnumParam = "product_brand_breakdown"
	AdgroupinsightsBreakdownsEnumParamProductCategoryBreakdown                  AdgroupinsightsBreakdownsEnumParam = "product_category_breakdown"
	AdgroupinsightsBreakdownsEnumParamProductCustomLabelX0Breakdown             AdgroupinsightsBreakdownsEnumParam = "product_custom_label_0_breakdown"
	AdgroupinsightsBreakdownsEnumParamProductCustomLabelX1Breakdown             AdgroupinsightsBreakdownsEnumParam = "product_custom_label_1_breakdown"
	AdgroupinsightsBreakdownsEnumParamProductCustomLabelX2Breakdown             AdgroupinsightsBreakdownsEnumParam = "product_custom_label_2_breakdown"
	AdgroupinsightsBreakdownsEnumParamProductCustomLabelX3Breakdown             AdgroupinsightsBreakdownsEnumParam = "product_custom_label_3_breakdown"
	AdgroupinsightsBreakdownsEnumParamProductCustomLabelX4Breakdown             AdgroupinsightsBreakdownsEnumParam = "product_custom_label_4_breakdown"
	AdgroupinsightsBreakdownsEnumParamProductGroupContentIDBreakdown            AdgroupinsightsBreakdownsEnumParam = "product_group_content_id_breakdown"
	AdgroupinsightsBreakdownsEnumParamProductID                                 AdgroupinsightsBreakdownsEnumParam = "product_id"
	AdgroupinsightsBreakdownsEnumParamPublisherPlatform                         AdgroupinsightsBreakdownsEnumParam = "publisher_platform"
	AdgroupinsightsBreakdownsEnumParamRedownload                                AdgroupinsightsBreakdownsEnumParam = "redownload"
	AdgroupinsightsBreakdownsEnumParamReelsTrendingTopic                        AdgroupinsightsBreakdownsEnumParam = "reels_trending_topic"
	AdgroupinsightsBreakdownsEnumParamRegion                                    AdgroupinsightsBreakdownsEnumParam = "region"
	AdgroupinsightsBreakdownsEnumParamRtaUgcTopic                               AdgroupinsightsBreakdownsEnumParam = "rta_ugc_topic"
	AdgroupinsightsBreakdownsEnumParamRuleSetID                                 AdgroupinsightsBreakdownsEnumParam = "rule_set_id"
	AdgroupinsightsBreakdownsEnumParamRuleSetName                               AdgroupinsightsBreakdownsEnumParam = "rule_set_name"
	AdgroupinsightsBreakdownsEnumParamSignalSourceBucket                        AdgroupinsightsBreakdownsEnumParam = "signal_source_bucket"
	AdgroupinsightsBreakdownsEnumParamSkanCampaignID                            AdgroupinsightsBreakdownsEnumParam = "skan_campaign_id"
	AdgroupinsightsBreakdownsEnumParamSkanConversionID                          AdgroupinsightsBreakdownsEnumParam = "skan_conversion_id"
	AdgroupinsightsBreakdownsEnumParamSkanVersion                               AdgroupinsightsBreakdownsEnumParam = "skan_version"
	AdgroupinsightsBreakdownsEnumParamSotAttributionModelType                   AdgroupinsightsBreakdownsEnumParam = "sot_attribution_model_type"
	AdgroupinsightsBreakdownsEnumParamSotAttributionWindow                      AdgroupinsightsBreakdownsEnumParam = "sot_attribution_window"
	AdgroupinsightsBreakdownsEnumParamSotChannel                                AdgroupinsightsBreakdownsEnumParam = "sot_channel"
	AdgroupinsightsBreakdownsEnumParamSotEventType                              AdgroupinsightsBreakdownsEnumParam = "sot_event_type"
	AdgroupinsightsBreakdownsEnumParamSotSource                                 AdgroupinsightsBreakdownsEnumParam = "sot_source"
	AdgroupinsightsBreakdownsEnumParamStandardEventContentType                  AdgroupinsightsBreakdownsEnumParam = "standard_event_content_type"
	AdgroupinsightsBreakdownsEnumParamTitleAsset                                AdgroupinsightsBreakdownsEnumParam = "title_asset"
	AdgroupinsightsBreakdownsEnumParamUserPersonaID                             AdgroupinsightsBreakdownsEnumParam = "user_persona_id"
	AdgroupinsightsBreakdownsEnumParamUserPersonaName                           AdgroupinsightsBreakdownsEnumParam = "user_persona_name"
	AdgroupinsightsBreakdownsEnumParamVideoAsset                                AdgroupinsightsBreakdownsEnumParam = "video_asset"
	AdgroupinsightsBreakdownsEnumParamZip                                       AdgroupinsightsBreakdownsEnumParam = "zip"
)

func (value AdgroupinsightsBreakdownsEnumParam) String() string {
	return string(value)
}
