package enums

type AdgrouppreviewsAdFormatEnumParam string

const (
	AdgrouppreviewsAdFormatEnumParamAudienceNetworkInstreamVideo        AdgrouppreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_INSTREAM_VIDEO"
	AdgrouppreviewsAdFormatEnumParamAudienceNetworkInstreamVideoMobile  AdgrouppreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_INSTREAM_VIDEO_MOBILE"
	AdgrouppreviewsAdFormatEnumParamAudienceNetworkOutstreamVideo       AdgrouppreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_OUTSTREAM_VIDEO"
	AdgrouppreviewsAdFormatEnumParamAudienceNetworkRewardedVideo        AdgrouppreviewsAdFormatEnumParam = "AUDIENCE_NETWORK_REWARDED_VIDEO"
	AdgrouppreviewsAdFormatEnumParamBizDiscoFeedMobile                  AdgrouppreviewsAdFormatEnumParam = "BIZ_DISCO_FEED_MOBILE"
	AdgrouppreviewsAdFormatEnumParamDesktopFeedStandard                 AdgrouppreviewsAdFormatEnumParam = "DESKTOP_FEED_STANDARD"
	AdgrouppreviewsAdFormatEnumParamFacebookIfuReelsMobile              AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_IFU_REELS_MOBILE"
	AdgrouppreviewsAdFormatEnumParamFacebookProfileFeedDesktop          AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_PROFILE_FEED_DESKTOP"
	AdgrouppreviewsAdFormatEnumParamFacebookProfileFeedMobile           AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_PROFILE_FEED_MOBILE"
	AdgrouppreviewsAdFormatEnumParamFacebookProfileReelsMobile          AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_PROFILE_REELS_MOBILE"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsBanner                 AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsBannerDesktop          AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_DESKTOP"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsBannerFeedAndroid      AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FEED_ANDROID"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsBannerFeedAndroidLarge AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FEED_ANDROID_LARGE"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsBannerFullscreenIos    AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FULLSCREEN_IOS"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsBannerFullscreenMobile AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_BANNER_FULLSCREEN_MOBILE"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsMobile                 AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_MOBILE"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsPostloop               AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_POSTLOOP"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsPostloopFeed           AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_POSTLOOP_FEED"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsSimilarProductsMobile  AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_SIMILAR_PRODUCTS_MOBILE"
	AdgrouppreviewsAdFormatEnumParamFacebookReelsSticker                AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_REELS_STICKER"
	AdgrouppreviewsAdFormatEnumParamFacebookStoryMobile                 AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_STORY_MOBILE"
	AdgrouppreviewsAdFormatEnumParamFacebookStoryStickerMobile          AdgrouppreviewsAdFormatEnumParam = "FACEBOOK_STORY_STICKER_MOBILE"
	AdgrouppreviewsAdFormatEnumParamInstagramExploreContextual          AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_EXPLORE_CONTEXTUAL"
	AdgrouppreviewsAdFormatEnumParamInstagramExploreGridHome            AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_EXPLORE_GRID_HOME"
	AdgrouppreviewsAdFormatEnumParamInstagramExploreImmersive           AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_EXPLORE_IMMERSIVE"
	AdgrouppreviewsAdFormatEnumParamInstagramFeedWeb                    AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_FEED_WEB"
	AdgrouppreviewsAdFormatEnumParamInstagramFeedWebMSite               AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_FEED_WEB_M_SITE"
	AdgrouppreviewsAdFormatEnumParamInstagramLeadGenMultiSubmitAds      AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_LEAD_GEN_MULTI_SUBMIT_ADS"
	AdgrouppreviewsAdFormatEnumParamInstagramProfileFeed                AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_PROFILE_FEED"
	AdgrouppreviewsAdFormatEnumParamInstagramProfileReels               AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_PROFILE_REELS"
	AdgrouppreviewsAdFormatEnumParamInstagramReels                      AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_REELS"
	AdgrouppreviewsAdFormatEnumParamInstagramReelsOverlay               AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_REELS_OVERLAY"
	AdgrouppreviewsAdFormatEnumParamInstagramReelsWeb                   AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_REELS_WEB"
	AdgrouppreviewsAdFormatEnumParamInstagramReelsWebMSite              AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_REELS_WEB_M_SITE"
	AdgrouppreviewsAdFormatEnumParamInstagramSearchChain                AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_SEARCH_CHAIN"
	AdgrouppreviewsAdFormatEnumParamInstagramSearchGrid                 AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_SEARCH_GRID"
	AdgrouppreviewsAdFormatEnumParamInstagramStandard                   AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_STANDARD"
	AdgrouppreviewsAdFormatEnumParamInstagramStory                      AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_STORY"
	AdgrouppreviewsAdFormatEnumParamInstagramStoryEffectTray            AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_STORY_EFFECT_TRAY"
	AdgrouppreviewsAdFormatEnumParamInstagramStoryWeb                   AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_STORY_WEB"
	AdgrouppreviewsAdFormatEnumParamInstagramStoryWebMSite              AdgrouppreviewsAdFormatEnumParam = "INSTAGRAM_STORY_WEB_M_SITE"
	AdgrouppreviewsAdFormatEnumParamInstantArticleRecirculationAd       AdgrouppreviewsAdFormatEnumParam = "INSTANT_ARTICLE_RECIRCULATION_AD"
	AdgrouppreviewsAdFormatEnumParamInstantArticleStandard              AdgrouppreviewsAdFormatEnumParam = "INSTANT_ARTICLE_STANDARD"
	AdgrouppreviewsAdFormatEnumParamInstreamBannerDesktop               AdgrouppreviewsAdFormatEnumParam = "INSTREAM_BANNER_DESKTOP"
	AdgrouppreviewsAdFormatEnumParamInstreamBannerFeedIos               AdgrouppreviewsAdFormatEnumParam = "INSTREAM_BANNER_FEED_IOS"
	AdgrouppreviewsAdFormatEnumParamInstreamBannerFullscreenIos         AdgrouppreviewsAdFormatEnumParam = "INSTREAM_BANNER_FULLSCREEN_IOS"
	AdgrouppreviewsAdFormatEnumParamInstreamBannerFullscreenMobile      AdgrouppreviewsAdFormatEnumParam = "INSTREAM_BANNER_FULLSCREEN_MOBILE"
	AdgrouppreviewsAdFormatEnumParamInstreamBannerImmersiveMobile       AdgrouppreviewsAdFormatEnumParam = "INSTREAM_BANNER_IMMERSIVE_MOBILE"
	AdgrouppreviewsAdFormatEnumParamInstreamBannerMobile                AdgrouppreviewsAdFormatEnumParam = "INSTREAM_BANNER_MOBILE"
	AdgrouppreviewsAdFormatEnumParamInstreamVideoDesktop                AdgrouppreviewsAdFormatEnumParam = "INSTREAM_VIDEO_DESKTOP"
	AdgrouppreviewsAdFormatEnumParamInstreamVideoFullscreenIos          AdgrouppreviewsAdFormatEnumParam = "INSTREAM_VIDEO_FULLSCREEN_IOS"
	AdgrouppreviewsAdFormatEnumParamInstreamVideoFullscreenMobile       AdgrouppreviewsAdFormatEnumParam = "INSTREAM_VIDEO_FULLSCREEN_MOBILE"
	AdgrouppreviewsAdFormatEnumParamInstreamVideoImage                  AdgrouppreviewsAdFormatEnumParam = "INSTREAM_VIDEO_IMAGE"
	AdgrouppreviewsAdFormatEnumParamInstreamVideoImmersiveMobile        AdgrouppreviewsAdFormatEnumParam = "INSTREAM_VIDEO_IMMERSIVE_MOBILE"
	AdgrouppreviewsAdFormatEnumParamInstreamVideoMobile                 AdgrouppreviewsAdFormatEnumParam = "INSTREAM_VIDEO_MOBILE"
	AdgrouppreviewsAdFormatEnumParamJobBrowserDesktop                   AdgrouppreviewsAdFormatEnumParam = "JOB_BROWSER_DESKTOP"
	AdgrouppreviewsAdFormatEnumParamJobBrowserMobile                    AdgrouppreviewsAdFormatEnumParam = "JOB_BROWSER_MOBILE"
	AdgrouppreviewsAdFormatEnumParamMarketplaceMobile                   AdgrouppreviewsAdFormatEnumParam = "MARKETPLACE_MOBILE"
	AdgrouppreviewsAdFormatEnumParamMessengerMobileInboxMedia           AdgrouppreviewsAdFormatEnumParam = "MESSENGER_MOBILE_INBOX_MEDIA"
	AdgrouppreviewsAdFormatEnumParamMessengerMobileStoryMedia           AdgrouppreviewsAdFormatEnumParam = "MESSENGER_MOBILE_STORY_MEDIA"
	AdgrouppreviewsAdFormatEnumParamMobileBanner                        AdgrouppreviewsAdFormatEnumParam = "MOBILE_BANNER"
	AdgrouppreviewsAdFormatEnumParamMobileFeedBasic                     AdgrouppreviewsAdFormatEnumParam = "MOBILE_FEED_BASIC"
	AdgrouppreviewsAdFormatEnumParamMobileFeedStandard                  AdgrouppreviewsAdFormatEnumParam = "MOBILE_FEED_STANDARD"
	AdgrouppreviewsAdFormatEnumParamMobileFullwidth                     AdgrouppreviewsAdFormatEnumParam = "MOBILE_FULLWIDTH"
	AdgrouppreviewsAdFormatEnumParamMobileInterstitial                  AdgrouppreviewsAdFormatEnumParam = "MOBILE_INTERSTITIAL"
	AdgrouppreviewsAdFormatEnumParamMobileMediumRectangle               AdgrouppreviewsAdFormatEnumParam = "MOBILE_MEDIUM_RECTANGLE"
	AdgrouppreviewsAdFormatEnumParamMobileNative                        AdgrouppreviewsAdFormatEnumParam = "MOBILE_NATIVE"
	AdgrouppreviewsAdFormatEnumParamRightColumnStandard                 AdgrouppreviewsAdFormatEnumParam = "RIGHT_COLUMN_STANDARD"
	AdgrouppreviewsAdFormatEnumParamSuggestedVideoDesktop               AdgrouppreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_DESKTOP"
	AdgrouppreviewsAdFormatEnumParamSuggestedVideoFullscreenMobile      AdgrouppreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_FULLSCREEN_MOBILE"
	AdgrouppreviewsAdFormatEnumParamSuggestedVideoImmersiveMobile       AdgrouppreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_IMMERSIVE_MOBILE"
	AdgrouppreviewsAdFormatEnumParamSuggestedVideoMobile                AdgrouppreviewsAdFormatEnumParam = "SUGGESTED_VIDEO_MOBILE"
	AdgrouppreviewsAdFormatEnumParamWatchFeedHome                       AdgrouppreviewsAdFormatEnumParam = "WATCH_FEED_HOME"
	AdgrouppreviewsAdFormatEnumParamWatchFeedMobile                     AdgrouppreviewsAdFormatEnumParam = "WATCH_FEED_MOBILE"
	AdgrouppreviewsAdFormatEnumParamWhatsappStatusMedia                 AdgrouppreviewsAdFormatEnumParam = "WHATSAPP_STATUS_MEDIA"
)

func (value AdgrouppreviewsAdFormatEnumParam) String() string {
	return string(value)
}
