package enums

type CustomaudiencedatasourceSubType string

const (
	CustomaudiencedatasourceSubTypeAdCampaign                      CustomaudiencedatasourceSubType = "AD_CAMPAIGN"
	CustomaudiencedatasourceSubTypeAnything                        CustomaudiencedatasourceSubType = "ANYTHING"
	CustomaudiencedatasourceSubTypeAppUsers                        CustomaudiencedatasourceSubType = "APP_USERS"
	CustomaudiencedatasourceSubTypeArEffectsEvents                 CustomaudiencedatasourceSubType = "AR_EFFECTS_EVENTS"
	CustomaudiencedatasourceSubTypeArExperienceEvents              CustomaudiencedatasourceSubType = "AR_EXPERIENCE_EVENTS"
	CustomaudiencedatasourceSubTypeCampaignConversions             CustomaudiencedatasourceSubType = "CAMPAIGN_CONVERSIONS"
	CustomaudiencedatasourceSubTypeCombinationCustomAudienceUsers  CustomaudiencedatasourceSubType = "COMBINATION_CUSTOM_AUDIENCE_USERS"
	CustomaudiencedatasourceSubTypeConstantContactsEmailHashes     CustomaudiencedatasourceSubType = "CONSTANT_CONTACTS_EMAIL_HASHES"
	CustomaudiencedatasourceSubTypeContactImporter                 CustomaudiencedatasourceSubType = "CONTACT_IMPORTER"
	CustomaudiencedatasourceSubTypeConversionPixelHits             CustomaudiencedatasourceSubType = "CONVERSION_PIXEL_HITS"
	CustomaudiencedatasourceSubTypeCopyPasteEmailHashes            CustomaudiencedatasourceSubType = "COPY_PASTE_EMAIL_HASHES"
	CustomaudiencedatasourceSubTypeCustomAudienceUsers             CustomaudiencedatasourceSubType = "CUSTOM_AUDIENCE_USERS"
	CustomaudiencedatasourceSubTypeCustomDataTargeting             CustomaudiencedatasourceSubType = "CUSTOM_DATA_TARGETING"
	CustomaudiencedatasourceSubTypeDataFile                        CustomaudiencedatasourceSubType = "DATA_FILE"
	CustomaudiencedatasourceSubTypeDynamicRule                     CustomaudiencedatasourceSubType = "DYNAMIC_RULE"
	CustomaudiencedatasourceSubTypeEngagementEventUsers            CustomaudiencedatasourceSubType = "ENGAGEMENT_EVENT_USERS"
	CustomaudiencedatasourceSubTypeExpandedAudience                CustomaudiencedatasourceSubType = "EXPANDED_AUDIENCE"
	CustomaudiencedatasourceSubTypeExternalIds                     CustomaudiencedatasourceSubType = "EXTERNAL_IDS"
	CustomaudiencedatasourceSubTypeExternalIdsMix                  CustomaudiencedatasourceSubType = "EXTERNAL_IDS_MIX"
	CustomaudiencedatasourceSubTypeFacebookWifiEvents              CustomaudiencedatasourceSubType = "FACEBOOK_WIFI_EVENTS"
	CustomaudiencedatasourceSubTypeFbEventSignals                  CustomaudiencedatasourceSubType = "FB_EVENT_SIGNALS"
	CustomaudiencedatasourceSubTypeFbPixelHits                     CustomaudiencedatasourceSubType = "FB_PIXEL_HITS"
	CustomaudiencedatasourceSubTypeGroupEvents                     CustomaudiencedatasourceSubType = "GROUP_EVENTS"
	CustomaudiencedatasourceSubTypeHashes                          CustomaudiencedatasourceSubType = "HASHES"
	CustomaudiencedatasourceSubTypeHashesOrUserIds                 CustomaudiencedatasourceSubType = "HASHES_OR_USER_IDS"
	CustomaudiencedatasourceSubTypeHouseholdExpansion              CustomaudiencedatasourceSubType = "HOUSEHOLD_EXPANSION"
	CustomaudiencedatasourceSubTypeIgBusinessEvents                CustomaudiencedatasourceSubType = "IG_BUSINESS_EVENTS"
	CustomaudiencedatasourceSubTypeIgPromotedPost                  CustomaudiencedatasourceSubType = "IG_PROMOTED_POST"
	CustomaudiencedatasourceSubTypeInstantArticleEvents            CustomaudiencedatasourceSubType = "INSTANT_ARTICLE_EVENTS"
	CustomaudiencedatasourceSubTypeLookalikePlatform               CustomaudiencedatasourceSubType = "LOOKALIKE_PLATFORM"
	CustomaudiencedatasourceSubTypeMailChimpEmailHashes            CustomaudiencedatasourceSubType = "MAIL_CHIMP_EMAIL_HASHES"
	CustomaudiencedatasourceSubTypeMarketplaceListings             CustomaudiencedatasourceSubType = "MARKETPLACE_LISTINGS"
	CustomaudiencedatasourceSubTypeMessageCampaign                 CustomaudiencedatasourceSubType = "MESSAGE_CAMPAIGN"
	CustomaudiencedatasourceSubTypeMessengerOnsiteSubscription     CustomaudiencedatasourceSubType = "MESSENGER_ONSITE_SUBSCRIPTION"
	CustomaudiencedatasourceSubTypeMobileAdvertiserIds             CustomaudiencedatasourceSubType = "MOBILE_ADVERTISER_IDS"
	CustomaudiencedatasourceSubTypeMobileAppCombinationEvents      CustomaudiencedatasourceSubType = "MOBILE_APP_COMBINATION_EVENTS"
	CustomaudiencedatasourceSubTypeMobileAppCustomAudienceUsers    CustomaudiencedatasourceSubType = "MOBILE_APP_CUSTOM_AUDIENCE_USERS"
	CustomaudiencedatasourceSubTypeMobileAppEvents                 CustomaudiencedatasourceSubType = "MOBILE_APP_EVENTS"
	CustomaudiencedatasourceSubTypeMulticountryCombination         CustomaudiencedatasourceSubType = "MULTICOUNTRY_COMBINATION"
	CustomaudiencedatasourceSubTypeMultiDataEvents                 CustomaudiencedatasourceSubType = "MULTI_DATA_EVENTS"
	CustomaudiencedatasourceSubTypeMultiEventSource                CustomaudiencedatasourceSubType = "MULTI_EVENT_SOURCE"
	CustomaudiencedatasourceSubTypeMultiHashes                     CustomaudiencedatasourceSubType = "MULTI_HASHES"
	CustomaudiencedatasourceSubTypeNothing                         CustomaudiencedatasourceSubType = "NOTHING"
	CustomaudiencedatasourceSubTypeOfflineEventUsers               CustomaudiencedatasourceSubType = "OFFLINE_EVENT_USERS"
	CustomaudiencedatasourceSubTypePageFans                        CustomaudiencedatasourceSubType = "PAGE_FANS"
	CustomaudiencedatasourceSubTypePageSmartAudience               CustomaudiencedatasourceSubType = "PAGE_SMART_AUDIENCE"
	CustomaudiencedatasourceSubTypePartnerCategoryUsers            CustomaudiencedatasourceSubType = "PARTNER_CATEGORY_USERS"
	CustomaudiencedatasourceSubTypePlaceVisits                     CustomaudiencedatasourceSubType = "PLACE_VISITS"
	CustomaudiencedatasourceSubTypePlatform                        CustomaudiencedatasourceSubType = "PLATFORM"
	CustomaudiencedatasourceSubTypePlatformUsers                   CustomaudiencedatasourceSubType = "PLATFORM_USERS"
	CustomaudiencedatasourceSubTypeSeedList                        CustomaudiencedatasourceSubType = "SEED_LIST"
	CustomaudiencedatasourceSubTypeSignalSource                    CustomaudiencedatasourceSubType = "SIGNAL_SOURCE"
	CustomaudiencedatasourceSubTypeSmartAudience                   CustomaudiencedatasourceSubType = "SMART_AUDIENCE"
	CustomaudiencedatasourceSubTypeStoreVisitEvents                CustomaudiencedatasourceSubType = "STORE_VISIT_EVENTS"
	CustomaudiencedatasourceSubTypeSubscriberList                  CustomaudiencedatasourceSubType = "SUBSCRIBER_LIST"
	CustomaudiencedatasourceSubTypeSExpr                           CustomaudiencedatasourceSubType = "S_EXPR"
	CustomaudiencedatasourceSubTypeTokens                          CustomaudiencedatasourceSubType = "TOKENS"
	CustomaudiencedatasourceSubTypeUserIds                         CustomaudiencedatasourceSubType = "USER_IDS"
	CustomaudiencedatasourceSubTypeVideoEvents                     CustomaudiencedatasourceSubType = "VIDEO_EVENTS"
	CustomaudiencedatasourceSubTypeVideoEventUsers                 CustomaudiencedatasourceSubType = "VIDEO_EVENT_USERS"
	CustomaudiencedatasourceSubTypeWebPixelCombinationEvents       CustomaudiencedatasourceSubType = "WEB_PIXEL_COMBINATION_EVENTS"
	CustomaudiencedatasourceSubTypeWebPixelHits                    CustomaudiencedatasourceSubType = "WEB_PIXEL_HITS"
	CustomaudiencedatasourceSubTypeWebPixelHitsCustomAudienceUsers CustomaudiencedatasourceSubType = "WEB_PIXEL_HITS_CUSTOM_AUDIENCE_USERS"
	CustomaudiencedatasourceSubTypeWhatsappSubscriberPool          CustomaudiencedatasourceSubType = "WHATSAPP_SUBSCRIBER_POOL"
)

func (value CustomaudiencedatasourceSubType) String() string {
	return string(value)
}
