package enums

type PageFoodStyles string

const (
	PageFoodStylesAfghani               PageFoodStyles = "Afghani"
	PageFoodStylesAmericanNew           PageFoodStyles = "American (New)"
	PageFoodStylesAmericanTraditional   PageFoodStyles = "American (Traditional)"
	PageFoodStylesAsianFusion           PageFoodStyles = "Asian Fusion"
	PageFoodStylesBarbeque              PageFoodStyles = "Barbeque"
	PageFoodStylesBrazilian             PageFoodStyles = "Brazilian"
	PageFoodStylesBreakfast             PageFoodStyles = "Breakfast"
	PageFoodStylesBritish               PageFoodStyles = "British"
	PageFoodStylesBrunch                PageFoodStyles = "Brunch"
	PageFoodStylesBuffets               PageFoodStyles = "Buffets"
	PageFoodStylesBurgers               PageFoodStyles = "Burgers"
	PageFoodStylesBurmese               PageFoodStyles = "Burmese"
	PageFoodStylesCajunCreole           PageFoodStyles = "Cajun/Creole"
	PageFoodStylesCaribbean             PageFoodStyles = "Caribbean"
	PageFoodStylesChinese               PageFoodStyles = "Chinese"
	PageFoodStylesCreperies             PageFoodStyles = "Creperies"
	PageFoodStylesCuban                 PageFoodStyles = "Cuban"
	PageFoodStylesDelis                 PageFoodStyles = "Delis"
	PageFoodStylesDiners                PageFoodStyles = "Diners"
	PageFoodStylesEthiopian             PageFoodStyles = "Ethiopian"
	PageFoodStylesFastFood              PageFoodStyles = "Fast Food"
	PageFoodStylesFilipino              PageFoodStyles = "Filipino"
	PageFoodStylesFondue                PageFoodStyles = "Fondue"
	PageFoodStylesFoodStands            PageFoodStyles = "Food Stands"
	PageFoodStylesFrench                PageFoodStyles = "French"
	PageFoodStylesGerman                PageFoodStyles = "German"
	PageFoodStylesGreekAndMediterranean PageFoodStyles = "Greek and Mediterranean"
	PageFoodStylesHawaiian              PageFoodStyles = "Hawaiian"
	PageFoodStylesHimalayanNepalese     PageFoodStyles = "Himalayan/Nepalese"
	PageFoodStylesHotDogs               PageFoodStyles = "Hot Dogs"
	PageFoodStylesIndianPakistani       PageFoodStyles = "Indian/Pakistani"
	PageFoodStylesIrish                 PageFoodStyles = "Irish"
	PageFoodStylesItalian               PageFoodStyles = "Italian"
	PageFoodStylesJapanese              PageFoodStyles = "Japanese"
	PageFoodStylesKorean                PageFoodStyles = "Korean"
	PageFoodStylesLatinAmerican         PageFoodStyles = "Latin American"
	PageFoodStylesMexican               PageFoodStyles = "Mexican"
	PageFoodStylesMiddleEastern         PageFoodStyles = "Middle Eastern"
	PageFoodStylesMoroccan              PageFoodStyles = "Moroccan"
	PageFoodStylesPizza                 PageFoodStyles = "Pizza"
	PageFoodStylesRussian               PageFoodStyles = "Russian"
	PageFoodStylesSandwiches            PageFoodStyles = "Sandwiches"
	PageFoodStylesSeafood               PageFoodStyles = "Seafood"
	PageFoodStylesSingaporean           PageFoodStyles = "Singaporean"
	PageFoodStylesSoulFood              PageFoodStyles = "Soul Food"
	PageFoodStylesSouthern              PageFoodStyles = "Southern"
	PageFoodStylesSpanishBasque         PageFoodStyles = "Spanish/Basque"
	PageFoodStylesSteakhouses           PageFoodStyles = "Steakhouses"
	PageFoodStylesSushiBars             PageFoodStyles = "Sushi Bars"
	PageFoodStylesTaiwanese             PageFoodStyles = "Taiwanese"
	PageFoodStylesTapasBars             PageFoodStyles = "Tapas Bars"
	PageFoodStylesTexMex                PageFoodStyles = "Tex-Mex"
	PageFoodStylesThai                  PageFoodStyles = "Thai"
	PageFoodStylesTurkish               PageFoodStyles = "Turkish"
	PageFoodStylesVegan                 PageFoodStyles = "Vegan"
	PageFoodStylesVegetarian            PageFoodStyles = "Vegetarian"
	PageFoodStylesVietnamese            PageFoodStyles = "Vietnamese"
)

func (value PageFoodStyles) String() string {
	return string(value)
}
