package enums

type ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParam string

const (
	ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParamHighAdPerformance ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParam = "high_ad_performance"
	ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParamMostAdsExperience ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParam = "most_ads_experience"
	ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParamMostRelevantForMe ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParam = "most_relevant_for_me"
	ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParamSimilarAudience   ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParam = "similar_audience"
	ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParamSimilarBrands     ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParam = "similar_brands"
)

func (value ShadowigusercreatorMarketplaceCreatorsRecommendationTypeEnumParam) String() string {
	return string(value)
}
