package enums

type ShadowiguserupcomingEventsNotificationSubtypesEnumParam string

const (
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamAfterEventX1DAY   ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "AFTER_EVENT_1DAY"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamAfterEventX2DAY   ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "AFTER_EVENT_2DAY"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamAfterEventX3DAY   ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "AFTER_EVENT_3DAY"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamAfterEventX4DAY   ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "AFTER_EVENT_4DAY"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamAfterEventX5DAY   ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "AFTER_EVENT_5DAY"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamAfterEventX6DAY   ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "AFTER_EVENT_6DAY"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamAfterEventX7DAY   ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "AFTER_EVENT_7DAY"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamBeforeEventX15MIN ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "BEFORE_EVENT_15MIN"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamBeforeEventX1DAY  ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "BEFORE_EVENT_1DAY"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamBeforeEventX1HOUR ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "BEFORE_EVENT_1HOUR"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamBeforeEventX2DAY  ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "BEFORE_EVENT_2DAY"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamEventStart        ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "EVENT_START"
	ShadowiguserupcomingEventsNotificationSubtypesEnumParamRescheduled       ShadowiguserupcomingEventsNotificationSubtypesEnumParam = "RESCHEDULED"
)

func (value ShadowiguserupcomingEventsNotificationSubtypesEnumParam) String() string {
	return string(value)
}
