package enums

type WhatsappbusinesspartnerclientverificationsubmissionVerificationStatus string

const (
	WhatsappbusinesspartnerclientverificationsubmissionVerificationStatusApproved  WhatsappbusinesspartnerclientverificationsubmissionVerificationStatus = "APPROVED"
	WhatsappbusinesspartnerclientverificationsubmissionVerificationStatusDiscarded WhatsappbusinesspartnerclientverificationsubmissionVerificationStatus = "DISCARDED"
	WhatsappbusinesspartnerclientverificationsubmissionVerificationStatusFailed    WhatsappbusinesspartnerclientverificationsubmissionVerificationStatus = "FAILED"
	WhatsappbusinesspartnerclientverificationsubmissionVerificationStatusPending   WhatsappbusinesspartnerclientverificationsubmissionVerificationStatus = "PENDING"
	WhatsappbusinesspartnerclientverificationsubmissionVerificationStatusRevoked   WhatsappbusinesspartnerclientverificationsubmissionVerificationStatus = "REVOKED"
)

func (value WhatsappbusinesspartnerclientverificationsubmissionVerificationStatus) String() string {
	return string(value)
}
