package enums

type WhatsappbusinessaccountmessageTemplatesSourceEnumParam string

const (
	WhatsappbusinessaccountmessageTemplatesSourceEnumParamAutoGenerated WhatsappbusinessaccountmessageTemplatesSourceEnumParam = "AUTO_GENERATED"
	WhatsappbusinessaccountmessageTemplatesSourceEnumParamManual        WhatsappbusinessaccountmessageTemplatesSourceEnumParam = "MANUAL"
)

func (value WhatsappbusinessaccountmessageTemplatesSourceEnumParam) String() string {
	return string(value)
}
