package objects

type AccessToken map[string]interface{}
type AdPlacementGroup map[string]interface{}
type AdsSingleChannelConversionEvent map[string]interface{}
type AdsValueAdjustmentRulePersona map[string]interface{}
type AEMAttribution map[string]interface{}
type AEMConversionConfig map[string]interface{}
type AEMConversionFilter map[string]interface{}
type ApplicationAppCapiSetting map[string]interface{}
type ApplicationAppEventTypes map[string]interface{}
type ApplicationDialogConfig map[string]interface{}
type ApplicationPermission map[string]interface{}
type ApplicationRoles map[string]interface{}
type ApplicationServerDomainInfos map[string]interface{}
type ApplicationSgwDatasetStatus map[string]interface{}
type ApplicationSgwInstallDeferralLink map[string]interface{}
type ApplicationSubscriptions map[string]interface{}
type BusinessMessagingFeatureStatus map[string]interface{}
type BusinessMessagingTemplateGroup map[string]interface{}
type ButtonAutoDetectionDeviceSelection map[string]interface{}
type CanvasAppAsset map[string]interface{}
type CloudbridgeSetting map[string]interface{}
type CommerceMerchantTaxSettings map[string]interface{}
type CommerceOrderCancellation map[string]interface{}
type CommerceOrderItem map[string]interface{}
type CommerceOrderPayment map[string]interface{}
type CommerceOrderRefund map[string]interface{}
type CommerceOrderShipment map[string]interface{}
type CommerceReturn map[string]interface{}
type DCPAppStoreOrder map[string]interface{}
type Doc map[string]interface{}
type ExternalAppDonation map[string]interface{}
type GamesIAPOrder map[string]interface{}
type GamesIAPProduct map[string]interface{}
type GroupFile map[string]interface{}
type IGGraphComment map[string]interface{}
type IGGraphCTXPartnerAppWelcomeMessageFlow map[string]interface{}
type IGGraphMedia map[string]interface{}
type IGGraphUser map[string]interface{}
type IGMediaExportForCAM map[string]interface{}
type IGUserExportForCAMInsightsResult map[string]interface{}
type InternalDonationForApp map[string]interface{}
type InvoiceCampaign map[string]interface{}
type MarketingMessagesCreativeOptimizationsOptIn map[string]interface{}
type Media map[string]interface{}
type MessengerAdsPartialAutomatedStep map[string]interface{}
type MobileSdkGk map[string]interface{}
type MonetizedDigitalStoreObject map[string]interface{}
type OfflineConversionDataSetStats map[string]interface{}
type PagePostExperimentVideoInsightsQueryResult map[string]interface{}
type PartnerIntegrationPullSession map[string]interface{}
type PollSettings map[string]interface{}
type Postish map[string]interface{}
type RefreshAccessToken map[string]interface{}
type ScheduledLiveVideo map[string]interface{}
type SignalsAttributionMetadataConfig map[string]interface{}
type SignalsUploadProgress map[string]interface{}
type StoryAttachment map[string]interface{}
type TestAccount map[string]interface{}
type ThreatPrivacyGroup map[string]interface{}
type UnifiedMessage map[string]interface{}
type UserProfile map[string]interface{}
type UserSubscribedAppsData map[string]interface{}
type VideoBoostMediaAd map[string]interface{}
type VideoCaption map[string]interface{}
type VideoCollaborators map[string]interface{}
type VideoPollOption map[string]interface{}
type WABACallAnalytics map[string]interface{}
type WABAConversationAnalytics map[string]interface{}
type WABAGroupAnalytics map[string]interface{}
type WABAPricingAnalytics map[string]interface{}
type WABATemplateAnalytics map[string]interface{}
type WABATemplateGroupAnalytics map[string]interface{}
type WhatsAppApplication map[string]interface{}
type WhatsAppBusinessAccountMessageTemplatePreview map[string]interface{}
type WhatsAppBusinessAccountMigrationIntent map[string]interface{}
type WhatsAppBusinessAccountPaymentConfiguration map[string]interface{}
type WhatsAppBusinessAccountPaymentConfigurations map[string]interface{}
type WhatsAppBusinessAccountToNumberCurrentStatus map[string]interface{}
type WhatsAppBusinessActivityHistory map[string]interface{}
type WhatsAppBusinessAudience map[string]interface{}
type WhatsAppBusinessCampaign map[string]interface{}
type WhatsAppBusinessCampaignSchedule map[string]interface{}
type WhatsAppBusinessHSM map[string]interface{}
type WhatsAppBusinessSolution map[string]interface{}
type WhatsAppExtension map[string]interface{}
