package objects

type CatalogSubVerticalList struct {
	Appliances                     *map[string]interface{} `json:"appliances,omitempty"`
	BabyFeeding                    *map[string]interface{} `json:"baby_feeding,omitempty"`
	BabyTransport                  *map[string]interface{} `json:"baby_transport,omitempty"`
	Beauty                         *map[string]interface{} `json:"beauty,omitempty"`
	Bedding                        *map[string]interface{} `json:"bedding,omitempty"`
	Cameras                        *map[string]interface{} `json:"cameras,omitempty"`
	CamerasAndPhotos               *map[string]interface{} `json:"cameras_and_photos,omitempty"`
	CellPhonesAndSmartWatches      *map[string]interface{} `json:"cell_phones_and_smart_watches,omitempty"`
	CleaningSupplies               *map[string]interface{} `json:"cleaning_supplies,omitempty"`
	CloOffer                       *map[string]interface{} `json:"clo_offer,omitempty"`
	Clothing                       *map[string]interface{} `json:"clothing,omitempty"`
	ClothingAccessories            *map[string]interface{} `json:"clothing_accessories,omitempty"`
	ComputerComponents             *map[string]interface{} `json:"computer_components,omitempty"`
	ComputersAndTablets            *map[string]interface{} `json:"computers_and_tablets,omitempty"`
	ComputersLaptopsAndTablets     *map[string]interface{} `json:"computers_laptops_and_tablets,omitempty"`
	DiaperingAndPottyTraining      *map[string]interface{} `json:"diapering_and_potty_training,omitempty"`
	ElectronicAccessoriesAndCables *map[string]interface{} `json:"electronic_accessories_and_cables,omitempty"`
	ElectronicsAccessories         *map[string]interface{} `json:"electronics_accessories,omitempty"`
	Furniture                      *map[string]interface{} `json:"furniture,omitempty"`
	Health                         *map[string]interface{} `json:"health,omitempty"`
	Home                           *map[string]interface{} `json:"home,omitempty"`
	HomeGoods                      *map[string]interface{} `json:"home_goods,omitempty"`
	HouseholdAndCleaningSupplies   *map[string]interface{} `json:"household_and_cleaning_supplies,omitempty"`
	Jewelry                        *map[string]interface{} `json:"jewelry,omitempty"`
	LargeAppliances                *map[string]interface{} `json:"large_appliances,omitempty"`
	LocalServiceBusinessItem       *map[string]interface{} `json:"local_service_business_item,omitempty"`
	LocalServiceBusinessRestaurant *map[string]interface{} `json:"local_service_business_restaurant,omitempty"`
	Nursery                        *map[string]interface{} `json:"nursery,omitempty"`
	PrintersAndScanners            *map[string]interface{} `json:"printers_and_scanners,omitempty"`
	PrintersScannersAndFaxMachines *map[string]interface{} `json:"printers_scanners_and_fax_machines,omitempty"`
	ProductDiscount                *map[string]interface{} `json:"product_discount,omitempty"`
	Projectors                     *map[string]interface{} `json:"projectors,omitempty"`
	Shoes                          *map[string]interface{} `json:"shoes,omitempty"`
	ShoesAndFootwear               *map[string]interface{} `json:"shoes_and_footwear,omitempty"`
	Software                       *map[string]interface{} `json:"software,omitempty"`
	TelevisionsAndMonitors         *map[string]interface{} `json:"televisions_and_monitors,omitempty"`
	TestChildSubVertical           *map[string]interface{} `json:"test_child_sub_vertical,omitempty"`
	TestGrandChildSubVertical      *map[string]interface{} `json:"test_grand_child_sub_vertical,omitempty"`
	TestSubVertical                *map[string]interface{} `json:"test_sub_vertical,omitempty"`
	TestSubVerticalAlias           *map[string]interface{} `json:"test_sub_vertical_alias,omitempty"`
	TestSubVerticalDataObject      *map[string]interface{} `json:"test_sub_vertical_data_object,omitempty"`
	ThirdPartyElectronics          *map[string]interface{} `json:"third_party_electronics,omitempty"`
	ThirdPartyToysAndGames         *map[string]interface{} `json:"third_party_toys_and_games,omitempty"`
	Toys                           *map[string]interface{} `json:"toys,omitempty"`
	ToysAndGames                   *map[string]interface{} `json:"toys_and_games,omitempty"`
	TvsAndMonitors                 *map[string]interface{} `json:"tvs_and_monitors,omitempty"`
	VehicleManufacturer            *map[string]interface{} `json:"vehicle_manufacturer,omitempty"`
	VideoGameConsolesAndVideoGames *map[string]interface{} `json:"video_game_consoles_and_video_games,omitempty"`
	VideoGamesAndConsoles          *map[string]interface{} `json:"video_games_and_consoles,omitempty"`
	VideoProjectors                *map[string]interface{} `json:"video_projectors,omitempty"`
	Watches                        *map[string]interface{} `json:"watches,omitempty"`
}
