package objects

import (
	core "github.com/shenzhencenter/meta-go/facebook"
)

type DeliveryWindow struct {
	Ac  *int     `json:"ac,omitempty"`
	Ad  *int     `json:"ad,omitempty"`
	Ae  *int     `json:"ae,omitempty"`
	Af  *int     `json:"af,omitempty"`
	Ag  *int     `json:"ag,omitempty"`
	Ai  *int     `json:"ai,omitempty"`
	Al  *int     `json:"al,omitempty"`
	All *int     `json:"all,omitempty"`
	Am  *int     `json:"am,omitempty"`
	An  *int     `json:"an,omitempty"`
	Ao  *int     `json:"ao,omitempty"`
	Aq  *int     `json:"aq,omitempty"`
	Ar  *int     `json:"ar,omitempty"`
	As  *int     `json:"as,omitempty"`
	At  *int     `json:"at,omitempty"`
	Au  *int     `json:"au,omitempty"`
	Aw  *int     `json:"aw,omitempty"`
	Ax  *int     `json:"ax,omitempty"`
	Az  *int     `json:"az,omitempty"`
	Ba  *int     `json:"ba,omitempty"`
	Bb  *int     `json:"bb,omitempty"`
	Bd  *int     `json:"bd,omitempty"`
	Be  *int     `json:"be,omitempty"`
	Bf  *int     `json:"bf,omitempty"`
	Bg  *int     `json:"bg,omitempty"`
	Bh  *int     `json:"bh,omitempty"`
	Bi  *int     `json:"bi,omitempty"`
	Bj  *int     `json:"bj,omitempty"`
	Bl  *int     `json:"bl,omitempty"`
	Bm  *int     `json:"bm,omitempty"`
	Bn  *int     `json:"bn,omitempty"`
	Bo  *int     `json:"bo,omitempty"`
	Bq  *int     `json:"bq,omitempty"`
	Br  *int     `json:"br,omitempty"`
	Bs  *int     `json:"bs,omitempty"`
	Bt  *int     `json:"bt,omitempty"`
	Bv  *int     `json:"bv,omitempty"`
	Bw  *int     `json:"bw,omitempty"`
	By  *int     `json:"by,omitempty"`
	Bz  *int     `json:"bz,omitempty"`
	Ca  *int     `json:"ca,omitempty"`
	Cc  *int     `json:"cc,omitempty"`
	Cd  *int     `json:"cd,omitempty"`
	Cf  *int     `json:"cf,omitempty"`
	Cg  *int     `json:"cg,omitempty"`
	Ch  *int     `json:"ch,omitempty"`
	Ci  *int     `json:"ci,omitempty"`
	Ck  *int     `json:"ck,omitempty"`
	Cl  *int     `json:"cl,omitempty"`
	Cm  *int     `json:"cm,omitempty"`
	Cn  *int     `json:"cn,omitempty"`
	Co  *int     `json:"co,omitempty"`
	Cr  *int     `json:"cr,omitempty"`
	Cu  *int     `json:"cu,omitempty"`
	Cv  *int     `json:"cv,omitempty"`
	Cw  *int     `json:"cw,omitempty"`
	Cx  *int     `json:"cx,omitempty"`
	Cy  *int     `json:"cy,omitempty"`
	Cz  *int     `json:"cz,omitempty"`
	De  *int     `json:"de,omitempty"`
	Dj  *int     `json:"dj,omitempty"`
	Dk  *int     `json:"dk,omitempty"`
	Dm  *int     `json:"dm,omitempty"`
	Do  *int     `json:"do,omitempty"`
	Dz  *int     `json:"dz,omitempty"`
	Ec  *int     `json:"ec,omitempty"`
	Ee  *int     `json:"ee,omitempty"`
	Eg  *int     `json:"eg,omitempty"`
	Eh  *int     `json:"eh,omitempty"`
	Er  *int     `json:"er,omitempty"`
	Es  *int     `json:"es,omitempty"`
	Et  *int     `json:"et,omitempty"`
	Fi  *int     `json:"fi,omitempty"`
	Fj  *int     `json:"fj,omitempty"`
	Fk  *int     `json:"fk,omitempty"`
	Fm  *int     `json:"fm,omitempty"`
	Fo  *int     `json:"fo,omitempty"`
	Fr  *int     `json:"fr,omitempty"`
	Ga  *int     `json:"ga,omitempty"`
	Gb  *int     `json:"gb,omitempty"`
	Gd  *int     `json:"gd,omitempty"`
	Ge  *int     `json:"ge,omitempty"`
	Gf  *int     `json:"gf,omitempty"`
	Gg  *int     `json:"gg,omitempty"`
	Gh  *int     `json:"gh,omitempty"`
	Gi  *int     `json:"gi,omitempty"`
	Gl  *int     `json:"gl,omitempty"`
	Gm  *int     `json:"gm,omitempty"`
	Gn  *int     `json:"gn,omitempty"`
	Gp  *int     `json:"gp,omitempty"`
	Gq  *int     `json:"gq,omitempty"`
	Gr  *int     `json:"gr,omitempty"`
	Gs  *int     `json:"gs,omitempty"`
	Gt  *int     `json:"gt,omitempty"`
	Gu  *int     `json:"gu,omitempty"`
	Gw  *int     `json:"gw,omitempty"`
	Gy  *int     `json:"gy,omitempty"`
	Hk  *int     `json:"hk,omitempty"`
	Hm  *int     `json:"hm,omitempty"`
	Hn  *int     `json:"hn,omitempty"`
	Hr  *int     `json:"hr,omitempty"`
	Ht  *int     `json:"ht,omitempty"`
	Hu  *int     `json:"hu,omitempty"`
	ID  *core.ID `json:"id,omitempty"`
	Ie  *int     `json:"ie,omitempty"`
	Il  *int     `json:"il,omitempty"`
	Im  *int     `json:"im,omitempty"`
	In  *int     `json:"in,omitempty"`
	Io  *int     `json:"io,omitempty"`
	Iq  *int     `json:"iq,omitempty"`
	Ir  *int     `json:"ir,omitempty"`
	Is  *int     `json:"is,omitempty"`
	It  *int     `json:"it,omitempty"`
	Je  *int     `json:"je,omitempty"`
	Jm  *int     `json:"jm,omitempty"`
	Jo  *int     `json:"jo,omitempty"`
	Jp  *int     `json:"jp,omitempty"`
	Ke  *int     `json:"ke,omitempty"`
	Kg  *int     `json:"kg,omitempty"`
	Kh  *int     `json:"kh,omitempty"`
	Ki  *int     `json:"ki,omitempty"`
	Km  *int     `json:"km,omitempty"`
	Kn  *int     `json:"kn,omitempty"`
	Kp  *int     `json:"kp,omitempty"`
	Kr  *int     `json:"kr,omitempty"`
	Kw  *int     `json:"kw,omitempty"`
	Ky  *int     `json:"ky,omitempty"`
	Kz  *int     `json:"kz,omitempty"`
	La  *int     `json:"la,omitempty"`
	Lb  *int     `json:"lb,omitempty"`
	Lc  *int     `json:"lc,omitempty"`
	Li  *int     `json:"li,omitempty"`
	Lk  *int     `json:"lk,omitempty"`
	Lr  *int     `json:"lr,omitempty"`
	Ls  *int     `json:"ls,omitempty"`
	Lt  *int     `json:"lt,omitempty"`
	Lu  *int     `json:"lu,omitempty"`
	Lv  *int     `json:"lv,omitempty"`
	Ly  *int     `json:"ly,omitempty"`
	Ma  *int     `json:"ma,omitempty"`
	Mc  *int     `json:"mc,omitempty"`
	Md  *int     `json:"md,omitempty"`
	Me  *int     `json:"me,omitempty"`
	Mf  *int     `json:"mf,omitempty"`
	Mg  *int     `json:"mg,omitempty"`
	Mh  *int     `json:"mh,omitempty"`
	Mk  *int     `json:"mk,omitempty"`
	Ml  *int     `json:"ml,omitempty"`
	Mm  *int     `json:"mm,omitempty"`
	Mn  *int     `json:"mn,omitempty"`
	Mo  *int     `json:"mo,omitempty"`
	Mp  *int     `json:"mp,omitempty"`
	Mq  *int     `json:"mq,omitempty"`
	Mr  *int     `json:"mr,omitempty"`
	Ms  *int     `json:"ms,omitempty"`
	Mt  *int     `json:"mt,omitempty"`
	Mu  *int     `json:"mu,omitempty"`
	Mv  *int     `json:"mv,omitempty"`
	Mw  *int     `json:"mw,omitempty"`
	Mx  *int     `json:"mx,omitempty"`
	My  *int     `json:"my,omitempty"`
	Mz  *int     `json:"mz,omitempty"`
	Na  *int     `json:"na,omitempty"`
	Nc  *int     `json:"nc,omitempty"`
	Ne  *int     `json:"ne,omitempty"`
	Nf  *int     `json:"nf,omitempty"`
	Ng  *int     `json:"ng,omitempty"`
	Ni  *int     `json:"ni,omitempty"`
	Nl  *int     `json:"nl,omitempty"`
	No  *int     `json:"no,omitempty"`
	Np  *int     `json:"np,omitempty"`
	Nr  *int     `json:"nr,omitempty"`
	Nu  *int     `json:"nu,omitempty"`
	Nz  *int     `json:"nz,omitempty"`
	Om  *int     `json:"om,omitempty"`
	Pa  *int     `json:"pa,omitempty"`
	Pe  *int     `json:"pe,omitempty"`
	Pf  *int     `json:"pf,omitempty"`
	Pg  *int     `json:"pg,omitempty"`
	Ph  *int     `json:"ph,omitempty"`
	Pk  *int     `json:"pk,omitempty"`
	Pl  *int     `json:"pl,omitempty"`
	Pm  *int     `json:"pm,omitempty"`
	Pn  *int     `json:"pn,omitempty"`
	Pr  *int     `json:"pr,omitempty"`
	Ps  *int     `json:"ps,omitempty"`
	Pt  *int     `json:"pt,omitempty"`
	Pw  *int     `json:"pw,omitempty"`
	Py  *int     `json:"py,omitempty"`
	Qa  *int     `json:"qa,omitempty"`
	Re  *int     `json:"re,omitempty"`
	Ro  *int     `json:"ro,omitempty"`
	Rs  *int     `json:"rs,omitempty"`
	Ru  *int     `json:"ru,omitempty"`
	Rw  *int     `json:"rw,omitempty"`
	Sa  *int     `json:"sa,omitempty"`
	Sb  *int     `json:"sb,omitempty"`
	Sc  *int     `json:"sc,omitempty"`
	Sd  *int     `json:"sd,omitempty"`
	Se  *int     `json:"se,omitempty"`
	Sg  *int     `json:"sg,omitempty"`
	Sh  *int     `json:"sh,omitempty"`
	Si  *int     `json:"si,omitempty"`
	Sj  *int     `json:"sj,omitempty"`
	Sk  *int     `json:"sk,omitempty"`
	Sl  *int     `json:"sl,omitempty"`
	Sm  *int     `json:"sm,omitempty"`
	Sn  *int     `json:"sn,omitempty"`
	So  *int     `json:"so,omitempty"`
	Sr  *int     `json:"sr,omitempty"`
	Ss  *int     `json:"ss,omitempty"`
	St  *int     `json:"st,omitempty"`
	Sv  *int     `json:"sv,omitempty"`
	Sx  *int     `json:"sx,omitempty"`
	Sy  *int     `json:"sy,omitempty"`
	Sz  *int     `json:"sz,omitempty"`
	Tc  *int     `json:"tc,omitempty"`
	Td  *int     `json:"td,omitempty"`
	Tf  *int     `json:"tf,omitempty"`
	Tg  *int     `json:"tg,omitempty"`
	Th  *int     `json:"th,omitempty"`
	Tj  *int     `json:"tj,omitempty"`
	Tk  *int     `json:"tk,omitempty"`
	Tl  *int     `json:"tl,omitempty"`
	Tm  *int     `json:"tm,omitempty"`
	Tn  *int     `json:"tn,omitempty"`
	To  *int     `json:"to,omitempty"`
	Tr  *int     `json:"tr,omitempty"`
	Tt  *int     `json:"tt,omitempty"`
	Tv  *int     `json:"tv,omitempty"`
	Tw  *int     `json:"tw,omitempty"`
	Tz  *int     `json:"tz,omitempty"`
	Ua  *int     `json:"ua,omitempty"`
	Ug  *int     `json:"ug,omitempty"`
	Um  *int     `json:"um,omitempty"`
	Us  *int     `json:"us,omitempty"`
	Uy  *int     `json:"uy,omitempty"`
	Uz  *int     `json:"uz,omitempty"`
	Va  *int     `json:"va,omitempty"`
	Vc  *int     `json:"vc,omitempty"`
	Ve  *int     `json:"ve,omitempty"`
	Vg  *int     `json:"vg,omitempty"`
	Vi  *int     `json:"vi,omitempty"`
	Vn  *int     `json:"vn,omitempty"`
	Vu  *int     `json:"vu,omitempty"`
	Wf  *int     `json:"wf,omitempty"`
	Ws  *int     `json:"ws,omitempty"`
	Xk  *int     `json:"xk,omitempty"`
	Ye  *int     `json:"ye,omitempty"`
	Yt  *int     `json:"yt,omitempty"`
	Za  *int     `json:"za,omitempty"`
	Zm  *int     `json:"zm,omitempty"`
	Zw  *int     `json:"zw,omitempty"`
}
