package objects

import (
	core "github.com/shenzhencenter/meta-go/facebook"
	"time"
)

type Page struct {
	About                                                *string                            `json:"about,omitempty"`
	AccessToken                                          *string                            `json:"access_token,omitempty"`
	AdCampaign                                           *AdSet                             `json:"ad_campaign,omitempty"`
	Affiliation                                          *string                            `json:"affiliation,omitempty"`
	AppID                                                *core.ID                           `json:"app_id,omitempty"`
	ArtistsWeLike                                        *string                            `json:"artists_we_like,omitempty"`
	Attire                                               *string                            `json:"attire,omitempty"`
	AvailablePromoOfferIds                               *[]map[string][]map[string]core.ID `json:"available_promo_offer_ids,omitempty"`
	Awards                                               *string                            `json:"awards,omitempty"`
	BandInterests                                        *string                            `json:"band_interests,omitempty"`
	BandMembers                                          *string                            `json:"band_members,omitempty"`
	BestPage                                             *Page                              `json:"best_page,omitempty"`
	Bio                                                  *string                            `json:"bio,omitempty"`
	Birthday                                             *string                            `json:"birthday,omitempty"`
	BookingAgent                                         *string                            `json:"booking_agent,omitempty"`
	BreakingNewsUsage                                    *map[string]interface{}            `json:"breaking_news_usage,omitempty"`
	Built                                                *string                            `json:"built,omitempty"`
	Business                                             *map[string]interface{}            `json:"business,omitempty"`
	CanCheckin                                           *bool                              `json:"can_checkin,omitempty"`
	CanPost                                              *bool                              `json:"can_post,omitempty"`
	Category                                             *string                            `json:"category,omitempty"`
	CategoryList                                         *[]PageCategory                    `json:"category_list,omitempty"`
	Checkins                                             *uint64                            `json:"checkins,omitempty"`
	CompanyOverview                                      *string                            `json:"company_overview,omitempty"`
	ConnectedInstagramAccount                            *IGUser                            `json:"connected_instagram_account,omitempty"`
	ConnectedPageBackedInstagramAccount                  *IGUser                            `json:"connected_page_backed_instagram_account,omitempty"`
	ContactAddress                                       *MailingAddress                    `json:"contact_address,omitempty"`
	CopyrightAttributionInsights                         *CopyrightAttributionInsights      `json:"copyright_attribution_insights,omitempty"`
	CopyrightWhitelistedIgPartners                       *[]string                          `json:"copyright_whitelisted_ig_partners,omitempty"`
	CountryPageLikes                                     *uint64                            `json:"country_page_likes,omitempty"`
	Cover                                                *CoverPhoto                        `json:"cover,omitempty"`
	CulinaryTeam                                         *string                            `json:"culinary_team,omitempty"`
	CurrentLocation                                      *string                            `json:"current_location,omitempty"`
	DeliveryAndPickupOptionInfo                          *[]string                          `json:"delivery_and_pickup_option_info,omitempty"`
	Description                                          *string                            `json:"description,omitempty"`
	DescriptionHTML                                      *string                            `json:"description_html,omitempty"`
	DifferentlyOpenOfferings                             *[]map[string]bool                 `json:"differently_open_offerings,omitempty"`
	DirectedBy                                           *string                            `json:"directed_by,omitempty"`
	DisplaySubtext                                       *string                            `json:"display_subtext,omitempty"`
	DisplayedMessageResponseTime                         *string                            `json:"displayed_message_response_time,omitempty"`
	DoesViewerHavePagePermissionLinkIg                   *bool                              `json:"does_viewer_have_page_permission_link_ig,omitempty"`
	Emails                                               *[]string                          `json:"emails,omitempty"`
	Engagement                                           *Engagement                        `json:"engagement,omitempty"`
	FanCount                                             *uint64                            `json:"fan_count,omitempty"`
	FeaturedVideo                                        *AdVideo                           `json:"featured_video,omitempty"`
	Features                                             *string                            `json:"features,omitempty"`
	FollowersCount                                       *uint64                            `json:"followers_count,omitempty"`
	FoodStyles                                           *[]string                          `json:"food_styles,omitempty"`
	Founded                                              *string                            `json:"founded,omitempty"`
	GeneralInfo                                          *string                            `json:"general_info,omitempty"`
	GeneralManager                                       *string                            `json:"general_manager,omitempty"`
	Genre                                                *string                            `json:"genre,omitempty"`
	GlobalBrandPageName                                  *string                            `json:"global_brand_page_name,omitempty"`
	GlobalBrandRootID                                    *core.ID                           `json:"global_brand_root_id,omitempty"`
	HasAddedApp                                          *bool                              `json:"has_added_app,omitempty"`
	HasLeadAccess                                        *HasLeadAccess                     `json:"has_lead_access,omitempty"`
	HasTransitionedToNewPageExperience                   *bool                              `json:"has_transitioned_to_new_page_experience,omitempty"`
	HasWhatsappBusinessNumber                            *bool                              `json:"has_whatsapp_business_number,omitempty"`
	HasWhatsappNumber                                    *bool                              `json:"has_whatsapp_number,omitempty"`
	Hometown                                             *string                            `json:"hometown,omitempty"`
	Hours                                                *map[string]string                 `json:"hours,omitempty"`
	ID                                                   *core.ID                           `json:"id,omitempty"`
	Impressum                                            *string                            `json:"impressum,omitempty"`
	Influences                                           *string                            `json:"influences,omitempty"`
	InstagramBusinessAccount                             *IGUser                            `json:"instagram_business_account,omitempty"`
	IsAlwaysOpen                                         *bool                              `json:"is_always_open,omitempty"`
	IsCallingEligible                                    *bool                              `json:"is_calling_eligible,omitempty"`
	IsChain                                              *bool                              `json:"is_chain,omitempty"`
	IsCommunityPage                                      *bool                              `json:"is_community_page,omitempty"`
	IsEligibleForBrandedContent                          *bool                              `json:"is_eligible_for_branded_content,omitempty"`
	IsEligibleForDisableConnectIgBtnForNonPageAdminAmWeb *bool                              `json:"is_eligible_for_disable_connect_ig_btn_for_non_page_admin_am_web,omitempty"`
	IsMessengerBotGetStartedEnabled                      *bool                              `json:"is_messenger_bot_get_started_enabled,omitempty"`
	IsMessengerPlatformBot                               *bool                              `json:"is_messenger_platform_bot,omitempty"`
	IsOwned                                              *bool                              `json:"is_owned,omitempty"`
	IsPermanentlyClosed                                  *bool                              `json:"is_permanently_closed,omitempty"`
	IsPublished                                          *bool                              `json:"is_published,omitempty"`
	IsUnclaimed                                          *bool                              `json:"is_unclaimed,omitempty"`
	IsVerified                                           *bool                              `json:"is_verified,omitempty"`
	IsWebhooksSubscribed                                 *bool                              `json:"is_webhooks_subscribed,omitempty"`
	Keywords                                             *map[string]interface{}            `json:"keywords,omitempty"`
	LeadgenTosAcceptanceTime                             *time.Time                         `json:"leadgen_tos_acceptance_time,omitempty"`
	LeadgenTosAccepted                                   *bool                              `json:"leadgen_tos_accepted,omitempty"`
	LeadgenTosAcceptingUser                              *User                              `json:"leadgen_tos_accepting_user,omitempty"`
	Link                                                 *string                            `json:"link,omitempty"`
	Location                                             *Location                          `json:"location,omitempty"`
	Members                                              *string                            `json:"members,omitempty"`
	MerchantID                                           *core.ID                           `json:"merchant_id,omitempty"`
	MerchantReviewStatus                                 *string                            `json:"merchant_review_status,omitempty"`
	MessagingFeatureStatus                               *MessagingFeatureStatus            `json:"messaging_feature_status,omitempty"`
	MessengerAdsDefaultIcebreakers                       *[]string                          `json:"messenger_ads_default_icebreakers,omitempty"`
	MessengerAdsDefaultQuickReplies                      *[]string                          `json:"messenger_ads_default_quick_replies,omitempty"`
	MessengerAdsQuickRepliesType                         *string                            `json:"messenger_ads_quick_replies_type,omitempty"`
	MiniShopStorefront                                   *Shop                              `json:"mini_shop_storefront,omitempty"`
	Mission                                              *string                            `json:"mission,omitempty"`
	Mpg                                                  *string                            `json:"mpg,omitempty"`
	Name                                                 *string                            `json:"name,omitempty"`
	NameWithLocationDescriptor                           *string                            `json:"name_with_location_descriptor,omitempty"`
	Network                                              *string                            `json:"network,omitempty"`
	NewLikeCount                                         *uint64                            `json:"new_like_count,omitempty"`
	OfferEligible                                        *bool                              `json:"offer_eligible,omitempty"`
	OverallStarRating                                    *float64                           `json:"overall_star_rating,omitempty"`
	OwnerBusiness                                        *Business                          `json:"owner_business,omitempty"`
	PageBackedThreadsAccountID                           *core.ID                           `json:"page_backed_threads_account_id,omitempty"`
	PageToken                                            *string                            `json:"page_token,omitempty"`
	ParentPage                                           *Page                              `json:"parent_page,omitempty"`
	Parking                                              *PageParking                       `json:"parking,omitempty"`
	PaymentOptions                                       *PagePaymentOptions                `json:"payment_options,omitempty"`
	PersonalInfo                                         *string                            `json:"personal_info,omitempty"`
	PersonalInterests                                    *string                            `json:"personal_interests,omitempty"`
	PharmaSafetyInfo                                     *string                            `json:"pharma_safety_info,omitempty"`
	Phone                                                *string                            `json:"phone,omitempty"`
	PickupOptions                                        *[]string                          `json:"pickup_options,omitempty"`
	PlaceType                                            *string                            `json:"place_type,omitempty"`
	PlotOutline                                          *string                            `json:"plot_outline,omitempty"`
	PreferredAudience                                    *Targeting                         `json:"preferred_audience,omitempty"`
	PressContact                                         *string                            `json:"press_contact,omitempty"`
	PriceRange                                           *string                            `json:"price_range,omitempty"`
	PriorityHours                                        *[]map[string]string               `json:"priority_hours,omitempty"`
	PrivacyInfoURL                                       *string                            `json:"privacy_info_url,omitempty"`
	ProducedBy                                           *string                            `json:"produced_by,omitempty"`
	Products                                             *string                            `json:"products,omitempty"`
	PromotionEligible                                    *bool                              `json:"promotion_eligible,omitempty"`
	PromotionIneligibleReason                            *string                            `json:"promotion_ineligible_reason,omitempty"`
	PublicTransit                                        *string                            `json:"public_transit,omitempty"`
	RatingCount                                          *uint64                            `json:"rating_count,omitempty"`
	Recipient                                            *string                            `json:"recipient,omitempty"`
	RecordLabel                                          *string                            `json:"record_label,omitempty"`
	ReleaseDate                                          *string                            `json:"release_date,omitempty"`
	RestaurantServices                                   *PageRestaurantServices            `json:"restaurant_services,omitempty"`
	RestaurantSpecialties                                *PageRestaurantSpecialties         `json:"restaurant_specialties,omitempty"`
	Schedule                                             *string                            `json:"schedule,omitempty"`
	ScreenplayBy                                         *string                            `json:"screenplay_by,omitempty"`
	Season                                               *string                            `json:"season,omitempty"`
	SingleLineAddress                                    *string                            `json:"single_line_address,omitempty"`
	Starring                                             *string                            `json:"starring,omitempty"`
	StartInfo                                            *PageStartInfo                     `json:"start_info,omitempty"`
	StoreCode                                            *string                            `json:"store_code,omitempty"`
	StoreLocationDescriptor                              *string                            `json:"store_location_descriptor,omitempty"`
	StoreNumber                                          *uint64                            `json:"store_number,omitempty"`
	Studio                                               *string                            `json:"studio,omitempty"`
	SupportsDonateButtonInLiveVideo                      *bool                              `json:"supports_donate_button_in_live_video,omitempty"`
	TalkingAboutCount                                    *uint64                            `json:"talking_about_count,omitempty"`
	TemporaryStatus                                      *string                            `json:"temporary_status,omitempty"`
	UnreadMessageCount                                   *uint64                            `json:"unread_message_count,omitempty"`
	UnreadNotifCount                                     *uint64                            `json:"unread_notif_count,omitempty"`
	UnseenMessageCount                                   *uint64                            `json:"unseen_message_count,omitempty"`
	UserAccessExpireTime                                 *time.Time                         `json:"user_access_expire_time,omitempty"`
	Username                                             *string                            `json:"username,omitempty"`
	VerificationStatus                                   *string                            `json:"verification_status,omitempty"`
	VoipInfo                                             *VoipInfo                          `json:"voip_info,omitempty"`
	Website                                              *string                            `json:"website,omitempty"`
	WereHereCount                                        *uint64                            `json:"were_here_count,omitempty"`
	WhatsappNumber                                       *string                            `json:"whatsapp_number,omitempty"`
	WrittenBy                                            *string                            `json:"written_by,omitempty"`
}
