package objects

import (
	core "github.com/shenzhencenter/facebook-go-sdk/facebook"
	"github.com/shenzhencenter/facebook-go-sdk/facebook/enums"
)

type ProductItem struct {
	AdditionalImageCdnUrls                                *[][]map[string]string                                  `json:"additional_image_cdn_urls,omitempty"`
	AdditionalImageUrls                                   *[]string                                               `json:"additional_image_urls,omitempty"`
	AdditionalVariantAttributes                           *[]map[string]string                                    `json:"additional_variant_attributes,omitempty"`
	AffiliateSellerRating                                 *float64                                                `json:"affiliate_seller_rating,omitempty"`
	AffiliateSellerRatingCount                            *int                                                    `json:"affiliate_seller_rating_count,omitempty"`
	AgeGroup                                              *enums.ProductitemAgeGroupEnum                          `json:"age_group,omitempty"`
	Applinks                                              *CatalogItemAppLinks                                    `json:"applinks,omitempty"`
	Availability                                          *enums.ProductitemAvailabilityEnum                      `json:"availability,omitempty"`
	BaseCommissionRate                                    *int                                                    `json:"base_commission_rate,omitempty"`
	Brand                                                 *string                                                 `json:"brand,omitempty"`
	BundleItems                                           *[]string                                               `json:"bundle_items,omitempty"`
	BundleRetailerIds                                     *[]core.ID                                              `json:"bundle_retailer_ids,omitempty"`
	CapabilitiesDisabledByUser                            *[]string                                               `json:"capabilities_disabled_by_user,omitempty"`
	CapabilityToReviewStatus                              *[]map[string]enums.ProductitemCapabilityToReviewStatus `json:"capability_to_review_status,omitempty"`
	Category                                              *string                                                 `json:"category,omitempty"`
	CategoryRanking                                       *int                                                    `json:"category_ranking,omitempty"`
	CategorySpecificFields                                *CatalogSubVerticalList                                 `json:"category_specific_fields,omitempty"`
	Color                                                 *string                                                 `json:"color,omitempty"`
	CommerceInsights                                      *ProductItemCommerceInsights                            `json:"commerce_insights,omitempty"`
	Condition                                             *enums.ProductitemConditionEnum                         `json:"condition,omitempty"`
	Currency                                              *string                                                 `json:"currency,omitempty"`
	CustomData                                            *[]map[string]string                                    `json:"custom_data,omitempty"`
	CustomLabelX0                                         *string                                                 `json:"custom_label_0,omitempty"`
	CustomLabelX1                                         *string                                                 `json:"custom_label_1,omitempty"`
	CustomLabelX2                                         *string                                                 `json:"custom_label_2,omitempty"`
	CustomLabelX3                                         *string                                                 `json:"custom_label_3,omitempty"`
	CustomLabelX4                                         *string                                                 `json:"custom_label_4,omitempty"`
	CustomNumberX0                                        *string                                                 `json:"custom_number_0,omitempty"`
	CustomNumberX1                                        *string                                                 `json:"custom_number_1,omitempty"`
	CustomNumberX2                                        *string                                                 `json:"custom_number_2,omitempty"`
	CustomNumberX3                                        *string                                                 `json:"custom_number_3,omitempty"`
	CustomNumberX4                                        *string                                                 `json:"custom_number_4,omitempty"`
	Description                                           *string                                                 `json:"description,omitempty"`
	Errors                                                *[]ProductItemError                                     `json:"errors,omitempty"`
	ExpirationDate                                        *string                                                 `json:"expiration_date,omitempty"`
	FbProductCategory                                     *string                                                 `json:"fb_product_category,omitempty"`
	Gender                                                *enums.ProductitemGenderEnum                            `json:"gender,omitempty"`
	GeneratedBackgroundImages                             *[]AIGeneratedProductImage                              `json:"generated_background_images,omitempty"`
	GeneratedBackgroundImagesAdUsage                      *bool                                                   `json:"generated_background_images_ad_usage,omitempty"`
	Gtin                                                  *string                                                 `json:"gtin,omitempty"`
	ID                                                    *core.ID                                                `json:"id,omitempty"`
	ImageCdnUrls                                          *[]map[string]string                                    `json:"image_cdn_urls,omitempty"`
	ImageFetchStatus                                      *enums.ProductitemImageFetchStatus                      `json:"image_fetch_status,omitempty"`
	ImageURL                                              *string                                                 `json:"image_url,omitempty"`
	Images                                                *[]string                                               `json:"images,omitempty"`
	ImporterAddress                                       *ProductItemImporterAddress                             `json:"importer_address,omitempty"`
	ImporterName                                          *string                                                 `json:"importer_name,omitempty"`
	InvalidationErrors                                    *[]ProductItemInvalidationError                         `json:"invalidation_errors,omitempty"`
	Inventory                                             *int                                                    `json:"inventory,omitempty"`
	IsBundleHero                                          *bool                                                   `json:"is_bundle_hero,omitempty"`
	LiveSpecialPrice                                      *string                                                 `json:"live_special_price,omitempty"`
	ManufacturerInfo                                      *string                                                 `json:"manufacturer_info,omitempty"`
	ManufacturerPartNumber                                *string                                                 `json:"manufacturer_part_number,omitempty"`
	MarkedForProductLaunch                                *string                                                 `json:"marked_for_product_launch,omitempty"`
	Material                                              *string                                                 `json:"material,omitempty"`
	MobileLink                                            *string                                                 `json:"mobile_link,omitempty"`
	Name                                                  *string                                                 `json:"name,omitempty"`
	OfferDisclaimer                                       *string                                                 `json:"offer_disclaimer,omitempty"`
	OfferDisclaimerURL                                    *string                                                 `json:"offer_disclaimer_url,omitempty"`
	OrderingIndex                                         *int                                                    `json:"ordering_index,omitempty"`
	OriginCountry                                         *string                                                 `json:"origin_country,omitempty"`
	OverallRanking                                        *int                                                    `json:"overall_ranking,omitempty"`
	ParentProductID                                       *core.ID                                                `json:"parent_product_id,omitempty"`
	Pattern                                               *string                                                 `json:"pattern,omitempty"`
	PostConversionSignalBasedEnforcementAppealEligibility *bool                                                   `json:"post_conversion_signal_based_enforcement_appeal_eligibility,omitempty"`
	Price                                                 *string                                                 `json:"price,omitempty"`
	ProductCatalog                                        *ProductCatalog                                         `json:"product_catalog,omitempty"`
	ProductFeed                                           *ProductFeed                                            `json:"product_feed,omitempty"`
	ProductGroup                                          *ProductGroup                                           `json:"product_group,omitempty"`
	ProductLocalInfo                                      *ProductItemLocalInfo                                   `json:"product_local_info,omitempty"`
	ProductRelationship                                   *string                                                 `json:"product_relationship,omitempty"`
	ProductType                                           *string                                                 `json:"product_type,omitempty"`
	QuantityToSellOnFacebook                              *int                                                    `json:"quantity_to_sell_on_facebook,omitempty"`
	RetailerID                                            *core.ID                                                `json:"retailer_id,omitempty"`
	RetailerProductGroupID                                *core.ID                                                `json:"retailer_product_group_id,omitempty"`
	ReviewRejectionReasons                                *[]string                                               `json:"review_rejection_reasons,omitempty"`
	ReviewStatus                                          *enums.ProductitemReviewStatus                          `json:"review_status,omitempty"`
	RichTextDescription                                   *string                                                 `json:"rich_text_description,omitempty"`
	SalePrice                                             *string                                                 `json:"sale_price,omitempty"`
	SalePriceEndDate                                      *string                                                 `json:"sale_price_end_date,omitempty"`
	SalePriceStartDate                                    *string                                                 `json:"sale_price_start_date,omitempty"`
	ShippingWeightUnit                                    *enums.ProductitemShippingWeightUnit                    `json:"shipping_weight_unit,omitempty"`
	ShippingWeightValue                                   *float64                                                `json:"shipping_weight_value,omitempty"`
	ShortDescription                                      *string                                                 `json:"short_description,omitempty"`
	Size                                                  *string                                                 `json:"size,omitempty"`
	StartDate                                             *string                                                 `json:"start_date,omitempty"`
	Status                                                *enums.ProductitemStatus                                `json:"status,omitempty"`
	Tags                                                  *[]string                                               `json:"tags,omitempty"`
	URL                                                   *string                                                 `json:"url,omitempty"`
	VendorID                                              *core.ID                                                `json:"vendor_id,omitempty"`
	VideoFetchStatus                                      *enums.ProductitemVideoFetchStatus                      `json:"video_fetch_status,omitempty"`
	Videos                                                *[]ProductItemVideoData                                 `json:"videos,omitempty"`
	Visibility                                            *enums.ProductitemVisibilityEnum                        `json:"visibility,omitempty"`
	WaComplianceCategory                                  *string                                                 `json:"wa_compliance_category,omitempty"`
}
