package objects

import (
	core "github.com/shenzhencenter/meta-go/facebook"
	"github.com/shenzhencenter/meta-go/facebook/enums"
)

type Targeting struct {
	AdgroupID                               *core.ID                                   `json:"adgroup_id,omitempty"`
	AgeMax                                  *uint64                                    `json:"age_max,omitempty"`
	AgeMin                                  *uint64                                    `json:"age_min,omitempty"`
	AgeRange                                *[]uint64                                  `json:"age_range,omitempty"`
	AppInstallState                         *string                                    `json:"app_install_state,omitempty"`
	AudienceNetworkPositions                *[]string                                  `json:"audience_network_positions,omitempty"`
	Behaviors                               *[]IDName                                  `json:"behaviors,omitempty"`
	BrandSafetyContentFilterLevels          *[]string                                  `json:"brand_safety_content_filter_levels,omitempty"`
	CatalogBasedTargeting                   *CatalogBasedTargeting                     `json:"catalog_based_targeting,omitempty"`
	Cities                                  *[]IDName                                  `json:"cities,omitempty"`
	CollegeYears                            *[]uint64                                  `json:"college_years,omitempty"`
	Connections                             *[]ConnectionsTargeting                    `json:"connections,omitempty"`
	ContextualTargetingCategories           *[]IDName                                  `json:"contextual_targeting_categories,omitempty"`
	Countries                               *[]string                                  `json:"countries,omitempty"`
	Country                                 *[]string                                  `json:"country,omitempty"`
	CountryGroups                           *[]string                                  `json:"country_groups,omitempty"`
	CustomAudiences                         *[]RawCustomAudience                       `json:"custom_audiences,omitempty"`
	DevicePlatforms                         *[]enums.TargetingDevicePlatforms          `json:"device_platforms,omitempty"`
	DirectInstallDevices                    *bool                                      `json:"direct_install_devices,omitempty"`
	DynamicAudienceIds                      *[]core.ID                                 `json:"dynamic_audience_ids,omitempty"`
	EducationMajors                         *[]IDName                                  `json:"education_majors,omitempty"`
	EducationSchools                        *[]IDName                                  `json:"education_schools,omitempty"`
	EducationStatuses                       *[]uint64                                  `json:"education_statuses,omitempty"`
	EffectiveAudienceNetworkPositions       *[]string                                  `json:"effective_audience_network_positions,omitempty"`
	EffectiveBrandSafetyContentFilterLevels *[]string                                  `json:"effective_brand_safety_content_filter_levels,omitempty"`
	EffectiveDevicePlatforms                *[]enums.TargetingEffectiveDevicePlatforms `json:"effective_device_platforms,omitempty"`
	EffectiveFacebookPositions              *[]string                                  `json:"effective_facebook_positions,omitempty"`
	EffectiveInstagramPositions             *[]string                                  `json:"effective_instagram_positions,omitempty"`
	EffectiveMessengerPositions             *[]string                                  `json:"effective_messenger_positions,omitempty"`
	EffectivePublisherPlatforms             *[]string                                  `json:"effective_publisher_platforms,omitempty"`
	EffectiveThreadsPositions               *[]string                                  `json:"effective_threads_positions,omitempty"`
	EffectiveWhatsappPositions              *[]string                                  `json:"effective_whatsapp_positions,omitempty"`
	EngagementSpecs                         *[]TargetingDynamicRule                    `json:"engagement_specs,omitempty"`
	EthnicAffinity                          *[]IDName                                  `json:"ethnic_affinity,omitempty"`
	ExcludeReachedSince                     *[]string                                  `json:"exclude_reached_since,omitempty"`
	ExcludedBrandSafetyContentTypes         *[]string                                  `json:"excluded_brand_safety_content_types,omitempty"`
	ExcludedConnections                     *[]ConnectionsTargeting                    `json:"excluded_connections,omitempty"`
	ExcludedCustomAudiences                 *[]RawCustomAudience                       `json:"excluded_custom_audiences,omitempty"`
	ExcludedDynamicAudienceIds              *[]core.ID                                 `json:"excluded_dynamic_audience_ids,omitempty"`
	ExcludedEngagementSpecs                 *[]TargetingDynamicRule                    `json:"excluded_engagement_specs,omitempty"`
	ExcludedGeoLocations                    *TargetingGeoLocation                      `json:"excluded_geo_locations,omitempty"`
	ExcludedMobileDeviceModel               *[]string                                  `json:"excluded_mobile_device_model,omitempty"`
	ExcludedProductAudienceSpecs            *[]TargetingProductAudienceSpec            `json:"excluded_product_audience_specs,omitempty"`
	ExcludedPublisherCategories             *[]string                                  `json:"excluded_publisher_categories,omitempty"`
	ExcludedPublisherListIds                *[]core.ID                                 `json:"excluded_publisher_list_ids,omitempty"`
	ExcludedUserDevice                      *[]string                                  `json:"excluded_user_device,omitempty"`
	Exclusions                              *FlexibleTargeting                         `json:"exclusions,omitempty"`
	FacebookPositions                       *[]string                                  `json:"facebook_positions,omitempty"`
	FamilyStatuses                          *[]IDName                                  `json:"family_statuses,omitempty"`
	FbDealID                                *core.ID                                   `json:"fb_deal_id,omitempty"`
	FlexibleSpec                            *[]FlexibleTargeting                       `json:"flexible_spec,omitempty"`
	FriendsOfConnections                    *[]ConnectionsTargeting                    `json:"friends_of_connections,omitempty"`
	Genders                                 *[]uint64                                  `json:"genders,omitempty"`
	Generation                              *[]IDName                                  `json:"generation,omitempty"`
	GeoLocations                            *TargetingGeoLocation                      `json:"geo_locations,omitempty"`
	HomeOwnership                           *[]IDName                                  `json:"home_ownership,omitempty"`
	HomeType                                *[]IDName                                  `json:"home_type,omitempty"`
	HomeValue                               *[]IDName                                  `json:"home_value,omitempty"`
	HouseholdComposition                    *[]IDName                                  `json:"household_composition,omitempty"`
	Income                                  *[]IDName                                  `json:"income,omitempty"`
	Industries                              *[]IDName                                  `json:"industries,omitempty"`
	InstagramPositions                      *[]string                                  `json:"instagram_positions,omitempty"`
	InstallStateApplication                 *string                                    `json:"install_state_application,omitempty"`
	InstreamVideoSkippableExcluded          *bool                                      `json:"instream_video_skippable_excluded,omitempty"`
	InterestedIn                            *[]uint64                                  `json:"interested_in,omitempty"`
	Interests                               *[]IDName                                  `json:"interests,omitempty"`
	IsWhatsappDestinationAd                 *bool                                      `json:"is_whatsapp_destination_ad,omitempty"`
	Keywords                                *[]string                                  `json:"keywords,omitempty"`
	LifeEvents                              *[]IDName                                  `json:"life_events,omitempty"`
	Locales                                 *[]uint64                                  `json:"locales,omitempty"`
	MessengerPositions                      *[]string                                  `json:"messenger_positions,omitempty"`
	Moms                                    *[]IDName                                  `json:"moms,omitempty"`
	NetWorth                                *[]IDName                                  `json:"net_worth,omitempty"`
	OfficeType                              *[]IDName                                  `json:"office_type,omitempty"`
	PlacePageSetIds                         *[]core.ID                                 `json:"place_page_set_ids,omitempty"`
	PoliticalViews                          *[]uint64                                  `json:"political_views,omitempty"`
	Politics                                *[]IDName                                  `json:"politics,omitempty"`
	ProductAudienceSpecs                    *[]TargetingProductAudienceSpec            `json:"product_audience_specs,omitempty"`
	ProspectingAudience                     *TargetingProspectingAudience              `json:"prospecting_audience,omitempty"`
	PublisherPlatforms                      *[]string                                  `json:"publisher_platforms,omitempty"`
	Radius                                  *string                                    `json:"radius,omitempty"`
	Regions                                 *[]IDName                                  `json:"regions,omitempty"`
	RelationshipStatuses                    *[]uint64                                  `json:"relationship_statuses,omitempty"`
	SiteCategory                            *[]string                                  `json:"site_category,omitempty"`
	SubscriberUniverse                      *TargetingSubscriberUniverse               `json:"subscriber_universe,omitempty"`
	TargetingAutomation                     *TargetingAutomation                       `json:"targeting_automation,omitempty"`
	TargetingOptimization                   *string                                    `json:"targeting_optimization,omitempty"`
	TargetingRelaxationTypes                *TargetingRelaxation                       `json:"targeting_relaxation_types,omitempty"`
	ThreadsPositions                        *[]string                                  `json:"threads_positions,omitempty"`
	UserAdclusters                          *[]IDName                                  `json:"user_adclusters,omitempty"`
	UserAgeUnknown                          *bool                                      `json:"user_age_unknown,omitempty"`
	UserDevice                              *[]string                                  `json:"user_device,omitempty"`
	UserEvent                               *[]uint64                                  `json:"user_event,omitempty"`
	UserOs                                  *[]string                                  `json:"user_os,omitempty"`
	WhatsappPositions                       *[]string                                  `json:"whatsapp_positions,omitempty"`
	WirelessCarrier                         *[]string                                  `json:"wireless_carrier,omitempty"`
	WorkEmployers                           *[]IDName                                  `json:"work_employers,omitempty"`
	WorkPositions                           *[]IDName                                  `json:"work_positions,omitempty"`
	Zips                                    *[]string                                  `json:"zips,omitempty"`
}
